repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
        language: python
        types: [text]
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            \.secrets\.baseline|
            package-lock\.json|
            coverage/.*|
            node_modules/.*
          )$

  - repo: local
    hooks:
      - id: check-hardcoded-supabase-secrets
        name: Check for hardcoded Supabase secrets
        entry: |
          bash -c '
          if grep -r "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9" --include="*.js" --include="*.ts" --include="*.json" . 2>/dev/null; then
            echo "❌ SECURITY: Hardcoded JWT token detected!"
            exit 1
          fi
          if grep -r "supabase.*service_role.*key" --include="*.js" --include="*.ts" . 2>/dev/null | grep -v "process.env" | grep -v "your_service_role_key"; then
            echo "❌ SECURITY: Hardcoded service role key detected!"
            exit 1
          fi
          '
        language: system
        pass_filenames: false
        always_run: true