module.exports = {
  apps: [
    {
      // o-core Metro (Port 8081)
      name: 'o-core',
      cwd: '/Users/cosmic/o-core',
      script: 'npm',
      args: 'start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
        NODE_OPTIONS: '--max_old_space_size=8192',
      },
      max_memory_restart: '1G',
      error_file: '/tmp/o-core-error.log',
      out_file: '/tmp/o-core-out.log',
      log_file: '/tmp/o-core-combined.log',
      time: true,
      merge_logs: false,
      autorestart: true,
      watch: false,
      ignore_watch: ['node_modules', '.expo'],
      max_restarts: 10,
      min_uptime: '5s',
      restart_delay: 3000,
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
    {
      // o-orig Metro (Port 8084)
      name: 'o-orig',
      cwd: '/Users/cosmic/o-orig',
      script: 'npm',
      args: 'start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
      },
      max_memory_restart: '1G',
      error_file: '/tmp/o-orig-error.log',
      out_file: '/tmp/o-orig-out.log',
      log_file: '/tmp/o-orig-combined.log',
      time: true,
      merge_logs: false,
      autorestart: true,
      watch: false,
      ignore_watch: ['node_modules', '.expo'],
      max_restarts: 10,
      min_uptime: '5s',
      restart_delay: 3000,
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
    {
      // BFF Proxy (Port 3001)
      name: 'bff',
      cwd: '/Users/cosmic/o-platform',
      script: 'npm',
      args: 'start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
      },
      max_memory_restart: '500M',
      error_file: '/tmp/bff-error.log',
      out_file: '/tmp/bff-out.log',
      log_file: '/tmp/bff-combined.log',
      time: true,
      merge_logs: false,
      autorestart: true,
      watch: false,
      ignore_watch: ['node_modules'],
      max_restarts: 10,
      min_uptime: '5s',
      restart_delay: 3000,
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
  ],
  // Clustering settings
  deploy: {
    production: {
      user: 'cosmic',
      host: 'localhost',
      ref: 'origin/main',
      repo: 'local',
    },
  },
};
