/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  type AnalyticsSummary,
  AnalyticsSummaryFromJSON,
  AnalyticsSummaryToJSON,
} from '../models/AnalyticsSummary';

/**
 *
 */
export class AnalyticsApi extends runtime.BaseAPI {
  /**
   * Creates request options for getAnalyticsSummary without sending the request
   */
  async getAnalyticsSummaryRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/analytics/summary`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns 7-day usage analytics for the authenticated API key.
   * Get analytics summary
   */
  async getAnalyticsSummaryRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AnalyticsSummary>> {
    const requestOptions = await this.getAnalyticsSummaryRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AnalyticsSummaryFromJSON(jsonValue)
    );
  }

  /**
   * Returns 7-day usage analytics for the authenticated API key.
   * Get analytics summary
   */
  async getAnalyticsSummary(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AnalyticsSummary> {
    const response = await this.getAnalyticsSummaryRaw(initOverrides);
    return await response.value();
  }
}
