/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  type AuthProfileResponse,
  AuthProfileResponseFromJSON,
  AuthProfileResponseToJSON,
} from '../models/AuthProfileResponse';
import {
  type AuthSessionResponse,
  AuthSessionResponseFromJSON,
  AuthSessionResponseToJSON,
} from '../models/AuthSessionResponse';
import {
  type LoginRequest,
  LoginRequestFromJSON,
  LoginRequestToJSON,
} from '../models/LoginRequest';
import {
  type PatchAuthProfileRequest,
  PatchAuthProfileRequestFromJSON,
  PatchAuthProfileRequestToJSON,
} from '../models/PatchAuthProfileRequest';
import {
  type PutAuthProfileRequest,
  PutAuthProfileRequestFromJSON,
  PutAuthProfileRequestToJSON,
} from '../models/PutAuthProfileRequest';
import {
  type RawProfileResponse,
  RawProfileResponseFromJSON,
  RawProfileResponseToJSON,
} from '../models/RawProfileResponse';
import {
  type RefreshTokenRequest,
  RefreshTokenRequestFromJSON,
  RefreshTokenRequestToJSON,
} from '../models/RefreshTokenRequest';
import {
  type RegisterRequest,
  RegisterRequestFromJSON,
  RegisterRequestToJSON,
} from '../models/RegisterRequest';
import {
  type TokenRefreshResponse,
  TokenRefreshResponseFromJSON,
  TokenRefreshResponseToJSON,
} from '../models/TokenRefreshResponse';

export interface LoginOperationRequest {
  loginRequest?: LoginRequest;
}

export interface PatchAuthProfileOperationRequest {
  patchAuthProfileRequest?: PatchAuthProfileRequest;
}

export interface PutAuthProfileOperationRequest {
  putAuthProfileRequest?: PutAuthProfileRequest;
}

export interface RefreshTokenOperationRequest {
  refreshTokenRequest?: RefreshTokenRequest;
}

export interface RegisterOperationRequest {
  registerRequest?: RegisterRequest;
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {
  /**
   * Creates request options for deleteAccount without sending the request
   */
  async deleteAccountRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('BearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/auth/account`;

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Delete account
   */
  async deleteAccountRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.deleteAccountRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Delete account
   */
  async deleteAccount(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
    await this.deleteAccountRaw(initOverrides);
  }

  /**
   * Creates request options for getAuthProfile without sending the request
   */
  async getAuthProfileRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('BearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/auth/profile`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns the authenticated user identity and API key metadata.
   * Get auth profile
   */
  async getAuthProfileRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthProfileResponse>> {
    const requestOptions = await this.getAuthProfileRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AuthProfileResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns the authenticated user identity and API key metadata.
   * Get auth profile
   */
  async getAuthProfile(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthProfileResponse> {
    const response = await this.getAuthProfileRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for login without sending the request
   */
  async loginRequestOpts(requestParameters: LoginOperationRequest): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/api/v1/auth/login`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: LoginRequestToJSON(requestParameters['loginRequest']),
    };
  }

  /**
   * Log in
   */
  async loginRaw(
    requestParameters: LoginOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthSessionResponse>> {
    const requestOptions = await this.loginRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AuthSessionResponseFromJSON(jsonValue)
    );
  }

  /**
   * Log in
   */
  async login(
    requestParameters: LoginOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthSessionResponse> {
    const response = await this.loginRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for logout without sending the request
   */
  async logoutRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('BearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/auth/logout`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Invalidates the current session. Requires Authorization header.
   * Log out
   */
  async logoutRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.logoutRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Invalidates the current session. Requires Authorization header.
   * Log out
   */
  async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
    await this.logoutRaw(initOverrides);
  }

  /**
   * Creates request options for patchAuthProfile without sending the request
   */
  async patchAuthProfileRequestOpts(
    requestParameters: PatchAuthProfileOperationRequest
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('BearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/auth/profile`;

    return {
      path: urlPath,
      method: 'PATCH',
      headers: headerParameters,
      query: queryParameters,
      body: PatchAuthProfileRequestToJSON(requestParameters['patchAuthProfileRequest']),
    };
  }

  /**
   * Update profile (partial)
   */
  async patchAuthProfileRaw(
    requestParameters: PatchAuthProfileOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<RawProfileResponse>> {
    const requestOptions = await this.patchAuthProfileRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RawProfileResponseFromJSON(jsonValue)
    );
  }

  /**
   * Update profile (partial)
   */
  async patchAuthProfile(
    requestParameters: PatchAuthProfileOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<RawProfileResponse> {
    const response = await this.patchAuthProfileRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for putAuthProfile without sending the request
   */
  async putAuthProfileRequestOpts(
    requestParameters: PutAuthProfileOperationRequest
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('BearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/auth/profile`;

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: PutAuthProfileRequestToJSON(requestParameters['putAuthProfileRequest']),
    };
  }

  /**
   * Superset of PATCH — also accepts preferences and data_retention_days (min 30).
   * Update profile (full)
   */
  async putAuthProfileRaw(
    requestParameters: PutAuthProfileOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<RawProfileResponse>> {
    const requestOptions = await this.putAuthProfileRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      RawProfileResponseFromJSON(jsonValue)
    );
  }

  /**
   * Superset of PATCH — also accepts preferences and data_retention_days (min 30).
   * Update profile (full)
   */
  async putAuthProfile(
    requestParameters: PutAuthProfileOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<RawProfileResponse> {
    const response = await this.putAuthProfileRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for refreshToken without sending the request
   */
  async refreshTokenRequestOpts(
    requestParameters: RefreshTokenOperationRequest
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/api/v1/auth/token/refresh`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: RefreshTokenRequestToJSON(requestParameters['refreshTokenRequest']),
    };
  }

  /**
   * Refresh access token
   */
  async refreshTokenRaw(
    requestParameters: RefreshTokenOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TokenRefreshResponse>> {
    const requestOptions = await this.refreshTokenRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TokenRefreshResponseFromJSON(jsonValue)
    );
  }

  /**
   * Refresh access token
   */
  async refreshToken(
    requestParameters: RefreshTokenOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TokenRefreshResponse> {
    const response = await this.refreshTokenRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for register without sending the request
   */
  async registerRequestOpts(
    requestParameters: RegisterOperationRequest
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/api/v1/auth/register`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: RegisterRequestToJSON(requestParameters['registerRequest']),
    };
  }

  /**
   * Register a new user
   */
  async registerRaw(
    requestParameters: RegisterOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthSessionResponse>> {
    const requestOptions = await this.registerRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AuthSessionResponseFromJSON(jsonValue)
    );
  }

  /**
   * Register a new user
   */
  async register(
    requestParameters: RegisterOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthSessionResponse> {
    const response = await this.registerRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
