/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  type CreateDeveloperAppRequest,
  CreateDeveloperAppRequestFromJSON,
  CreateDeveloperAppRequestToJSON,
} from '../models/CreateDeveloperAppRequest';
import {
  type GetMarketplaceApp200Response,
  GetMarketplaceApp200ResponseFromJSON,
  GetMarketplaceApp200ResponseToJSON,
} from '../models/GetMarketplaceApp200Response';
import {
  type ListTrendingApps200Response,
  ListTrendingApps200ResponseFromJSON,
  ListTrendingApps200ResponseToJSON,
} from '../models/ListTrendingApps200Response';
import {
  type SubmitDeveloperApp200Response,
  SubmitDeveloperApp200ResponseFromJSON,
  SubmitDeveloperApp200ResponseToJSON,
} from '../models/SubmitDeveloperApp200Response';
import {
  type UpdateDeveloperAppRequest,
  UpdateDeveloperAppRequestFromJSON,
  UpdateDeveloperAppRequestToJSON,
} from '../models/UpdateDeveloperAppRequest';

export interface CreateDeveloperAppOperationRequest {
  createDeveloperAppRequest?: CreateDeveloperAppRequest;
}

export interface DeleteDeveloperAppRequest {
  appId: string;
}

export interface GetDeveloperAppRequest {
  appId: string;
}

export interface ResubmitDeveloperAppRequest {
  appId: string;
  updateDeveloperAppRequest?: UpdateDeveloperAppRequest;
}

export interface SubmitDeveloperAppRequest {
  appId: string;
}

export interface UpdateDeveloperAppOperationRequest {
  appId: string;
  updateDeveloperAppRequest?: UpdateDeveloperAppRequest;
}

/**
 *
 */
export class DeveloperApi extends runtime.BaseAPI {
  /**
   * Creates request options for createDeveloperApp without sending the request
   */
  async createDeveloperAppRequestOpts(
    requestParameters: CreateDeveloperAppOperationRequest
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/developer/apps`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: CreateDeveloperAppRequestToJSON(requestParameters['createDeveloperAppRequest']),
    };
  }

  /**
   * Create app
   */
  async createDeveloperAppRaw(
    requestParameters: CreateDeveloperAppOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetMarketplaceApp200Response>> {
    const requestOptions = await this.createDeveloperAppRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetMarketplaceApp200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Create app
   */
  async createDeveloperApp(
    requestParameters: CreateDeveloperAppOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GetMarketplaceApp200Response> {
    const response = await this.createDeveloperAppRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for deleteDeveloperApp without sending the request
   */
  async deleteDeveloperAppRequestOpts(
    requestParameters: DeleteDeveloperAppRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['appId'] == null) {
      throw new runtime.RequiredError(
        'appId',
        'Required parameter "appId" was null or undefined when calling deleteDeveloperApp().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/developer/apps/{appId}`;
    urlPath = urlPath.replace('{appId}', encodeURIComponent(String(requestParameters['appId'])));

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Only draft apps can be deleted. Approved apps must be deactivated first.
   * Delete app
   */
  async deleteDeveloperAppRaw(
    requestParameters: DeleteDeveloperAppRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.deleteDeveloperAppRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Only draft apps can be deleted. Approved apps must be deactivated first.
   * Delete app
   */
  async deleteDeveloperApp(
    requestParameters: DeleteDeveloperAppRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.deleteDeveloperAppRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for getDeveloperApp without sending the request
   */
  async getDeveloperAppRequestOpts(
    requestParameters: GetDeveloperAppRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['appId'] == null) {
      throw new runtime.RequiredError(
        'appId',
        'Required parameter "appId" was null or undefined when calling getDeveloperApp().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/developer/apps/{appId}`;
    urlPath = urlPath.replace('{appId}', encodeURIComponent(String(requestParameters['appId'])));

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Get developer app
   */
  async getDeveloperAppRaw(
    requestParameters: GetDeveloperAppRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetMarketplaceApp200Response>> {
    const requestOptions = await this.getDeveloperAppRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetMarketplaceApp200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Get developer app
   */
  async getDeveloperApp(
    requestParameters: GetDeveloperAppRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GetMarketplaceApp200Response> {
    const response = await this.getDeveloperAppRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listDeveloperApps without sending the request
   */
  async listDeveloperAppsRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/developer/apps`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns all marketplace apps owned by the authenticated developer.
   * List developer apps
   */
  async listDeveloperAppsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListTrendingApps200Response>> {
    const requestOptions = await this.listDeveloperAppsRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListTrendingApps200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns all marketplace apps owned by the authenticated developer.
   * List developer apps
   */
  async listDeveloperApps(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListTrendingApps200Response> {
    const response = await this.listDeveloperAppsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for resubmitDeveloperApp without sending the request
   */
  async resubmitDeveloperAppRequestOpts(
    requestParameters: ResubmitDeveloperAppRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['appId'] == null) {
      throw new runtime.RequiredError(
        'appId',
        'Required parameter "appId" was null or undefined when calling resubmitDeveloperApp().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/developer/apps/{appId}/resubmit`;
    urlPath = urlPath.replace('{appId}', encodeURIComponent(String(requestParameters['appId'])));

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: UpdateDeveloperAppRequestToJSON(requestParameters['updateDeveloperAppRequest']),
    };
  }

  /**
   * Updates fields and resubmits a rejected app for review.
   * Resubmit rejected app
   */
  async resubmitDeveloperAppRaw(
    requestParameters: ResubmitDeveloperAppRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<SubmitDeveloperApp200Response>> {
    const requestOptions = await this.resubmitDeveloperAppRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SubmitDeveloperApp200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Updates fields and resubmits a rejected app for review.
   * Resubmit rejected app
   */
  async resubmitDeveloperApp(
    requestParameters: ResubmitDeveloperAppRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<SubmitDeveloperApp200Response> {
    const response = await this.resubmitDeveloperAppRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for submitDeveloperApp without sending the request
   */
  async submitDeveloperAppRequestOpts(
    requestParameters: SubmitDeveloperAppRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['appId'] == null) {
      throw new runtime.RequiredError(
        'appId',
        'Required parameter "appId" was null or undefined when calling submitDeveloperApp().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/developer/apps/{appId}/submit`;
    urlPath = urlPath.replace('{appId}', encodeURIComponent(String(requestParameters['appId'])));

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Transitions app from draft → pending_review.
   * Submit app for review
   */
  async submitDeveloperAppRaw(
    requestParameters: SubmitDeveloperAppRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<SubmitDeveloperApp200Response>> {
    const requestOptions = await this.submitDeveloperAppRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SubmitDeveloperApp200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Transitions app from draft → pending_review.
   * Submit app for review
   */
  async submitDeveloperApp(
    requestParameters: SubmitDeveloperAppRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<SubmitDeveloperApp200Response> {
    const response = await this.submitDeveloperAppRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for updateDeveloperApp without sending the request
   */
  async updateDeveloperAppRequestOpts(
    requestParameters: UpdateDeveloperAppOperationRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['appId'] == null) {
      throw new runtime.RequiredError(
        'appId',
        'Required parameter "appId" was null or undefined when calling updateDeveloperApp().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/developer/apps/{appId}`;
    urlPath = urlPath.replace('{appId}', encodeURIComponent(String(requestParameters['appId'])));

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: UpdateDeveloperAppRequestToJSON(requestParameters['updateDeveloperAppRequest']),
    };
  }

  /**
   * Update app
   */
  async updateDeveloperAppRaw(
    requestParameters: UpdateDeveloperAppOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetMarketplaceApp200Response>> {
    const requestOptions = await this.updateDeveloperAppRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetMarketplaceApp200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Update app
   */
  async updateDeveloperApp(
    requestParameters: UpdateDeveloperAppOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GetMarketplaceApp200Response> {
    const response = await this.updateDeveloperAppRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
