/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  type GetStorage200Response,
  GetStorage200ResponseFromJSON,
  GetStorage200ResponseToJSON,
} from '../models/GetStorage200Response';
import {
  type ListEntries200Response,
  ListEntries200ResponseFromJSON,
  ListEntries200ResponseToJSON,
} from '../models/ListEntries200Response';
import {
  type ListTemplates200Response,
  ListTemplates200ResponseFromJSON,
  ListTemplates200ResponseToJSON,
} from '../models/ListTemplates200Response';

export interface ListEntriesRequest {
  limit?: number;
  offset?: number;
}

/**
 *
 */
export class EntriesApi extends runtime.BaseAPI {
  /**
   * Creates request options for getStorage without sending the request
   */
  async getStorageRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/storage`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns storage usage for the authenticated user. Not yet implemented — returns empty object.
   * Get storage info
   */
  async getStorageRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetStorage200Response>> {
    const requestOptions = await this.getStorageRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetStorage200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns storage usage for the authenticated user. Not yet implemented — returns empty object.
   * Get storage info
   */
  async getStorage(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GetStorage200Response> {
    const response = await this.getStorageRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listEntries without sending the request
   */
  async listEntriesRequestOpts(
    requestParameters: ListEntriesRequest
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit'];
    }

    if (requestParameters['offset'] != null) {
      queryParameters['offset'] = requestParameters['offset'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/entries`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns paginated entries for the authenticated user\'s profile.
   * List entries
   */
  async listEntriesRaw(
    requestParameters: ListEntriesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListEntries200Response>> {
    const requestOptions = await this.listEntriesRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListEntries200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns paginated entries for the authenticated user\'s profile.
   * List entries
   */
  async listEntries(
    requestParameters: ListEntriesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListEntries200Response> {
    const response = await this.listEntriesRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listTemplates without sending the request
   */
  async listTemplatesRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/templates`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns available entry templates. Not yet implemented — returns empty list.
   * List templates
   */
  async listTemplatesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListTemplates200Response>> {
    const requestOptions = await this.listTemplatesRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListTemplates200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns available entry templates. Not yet implemented — returns empty list.
   * List templates
   */
  async listTemplates(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListTemplates200Response> {
    const response = await this.listTemplatesRaw(initOverrides);
    return await response.value();
  }
}
