/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  type CreateEvent201Response,
  CreateEvent201ResponseFromJSON,
  CreateEvent201ResponseToJSON,
} from '../models/CreateEvent201Response';
import {
  type CreateEventRequest,
  CreateEventRequestFromJSON,
  CreateEventRequestToJSON,
} from '../models/CreateEventRequest';
import {
  type GetEvent200Response,
  GetEvent200ResponseFromJSON,
  GetEvent200ResponseToJSON,
} from '../models/GetEvent200Response';
import {
  type ListEvents200Response,
  ListEvents200ResponseFromJSON,
  ListEvents200ResponseToJSON,
} from '../models/ListEvents200Response';

export interface CreateEventOperationRequest {
  createEventRequest?: CreateEventRequest;
}

export interface GetEventRequest {
  eventId: string;
}

export interface ListEventsRequest {
  category?: string;
  startDate?: Date;
  endDate?: Date;
  limit?: number;
  offset?: number;
}

/**
 *
 */
export class EventsApi extends runtime.BaseAPI {
  /**
   * Creates request options for createEvent without sending the request
   */
  async createEventRequestOpts(
    requestParameters: CreateEventOperationRequest
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('BearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/oriva/events`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: CreateEventRequestToJSON(requestParameters['createEventRequest']),
    };
  }

  /**
   * Create event
   */
  async createEventRaw(
    requestParameters: CreateEventOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<CreateEvent201Response>> {
    const requestOptions = await this.createEventRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateEvent201ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Create event
   */
  async createEvent(
    requestParameters: CreateEventOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<CreateEvent201Response> {
    const response = await this.createEventRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getEvent without sending the request
   */
  async getEventRequestOpts(requestParameters: GetEventRequest): Promise<runtime.RequestOpts> {
    if (requestParameters['eventId'] == null) {
      throw new runtime.RequiredError(
        'eventId',
        'Required parameter "eventId" was null or undefined when calling getEvent().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/oriva/events/{eventId}`;
    urlPath = urlPath.replace(
      '{eventId}',
      encodeURIComponent(String(requestParameters['eventId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Get event
   */
  async getEventRaw(
    requestParameters: GetEventRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetEvent200Response>> {
    const requestOptions = await this.getEventRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetEvent200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Get event
   */
  async getEvent(
    requestParameters: GetEventRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GetEvent200Response> {
    const response = await this.getEventRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listEvents without sending the request
   */
  async listEventsRequestOpts(requestParameters: ListEventsRequest): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters['category'] != null) {
      queryParameters['category'] = requestParameters['category'];
    }

    if (requestParameters['startDate'] != null) {
      queryParameters['startDate'] = (requestParameters['startDate'] as any).toISOString();
    }

    if (requestParameters['endDate'] != null) {
      queryParameters['endDate'] = (requestParameters['endDate'] as any).toISOString();
    }

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit'];
    }

    if (requestParameters['offset'] != null) {
      queryParameters['offset'] = requestParameters['offset'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/oriva/events`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns active events with optional filtering by category and date range.
   * List events
   */
  async listEventsRaw(
    requestParameters: ListEventsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListEvents200Response>> {
    const requestOptions = await this.listEventsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListEvents200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns active events with optional filtering by category and date range.
   * List events
   */
  async listEvents(
    requestParameters: ListEventsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListEvents200Response> {
    const response = await this.listEventsRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
