/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  type ListGroupMembers200Response,
  ListGroupMembers200ResponseFromJSON,
  ListGroupMembers200ResponseToJSON,
} from '../models/ListGroupMembers200Response';
import {
  type ListGroups200Response,
  ListGroups200ResponseFromJSON,
  ListGroups200ResponseToJSON,
} from '../models/ListGroups200Response';

export interface ListGroupMembersRequest {
  groupId: string;
}

/**
 *
 */
export class GroupsApi extends runtime.BaseAPI {
  /**
   * Creates request options for listGroupMembers without sending the request
   */
  async listGroupMembersRequestOpts(
    requestParameters: ListGroupMembersRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['groupId'] == null) {
      throw new runtime.RequiredError(
        'groupId',
        'Required parameter "groupId" was null or undefined when calling listGroupMembers().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/groups/{groupId}/members`;
    urlPath = urlPath.replace(
      '{groupId}',
      encodeURIComponent(String(requestParameters['groupId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns members of a group. Requires the caller to be the creator or a member.
   * Get group members
   */
  async listGroupMembersRaw(
    requestParameters: ListGroupMembersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListGroupMembers200Response>> {
    const requestOptions = await this.listGroupMembersRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListGroupMembers200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns members of a group. Requires the caller to be the creator or a member.
   * Get group members
   */
  async listGroupMembers(
    requestParameters: ListGroupMembersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListGroupMembers200Response> {
    const response = await this.listGroupMembersRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listGroups without sending the request
   */
  async listGroupsRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/groups`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns all groups the authenticated user created or joined.
   * List groups
   */
  async listGroupsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListGroups200Response>> {
    const requestOptions = await this.listGroupsRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListGroups200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns all groups the authenticated user created or joined.
   * List groups
   */
  async listGroups(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListGroups200Response> {
    const response = await this.listGroupsRaw(initOverrides);
    return await response.value();
  }
}
