/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  type GetCategoryTree200Response,
  GetCategoryTree200ResponseFromJSON,
  GetCategoryTree200ResponseToJSON,
} from '../models/GetCategoryTree200Response';
import {
  type GetMarketplaceApp200Response,
  GetMarketplaceApp200ResponseFromJSON,
  GetMarketplaceApp200ResponseToJSON,
} from '../models/GetMarketplaceApp200Response';
import {
  type GetMarketplaceCategory200Response,
  GetMarketplaceCategory200ResponseFromJSON,
  GetMarketplaceCategory200ResponseToJSON,
} from '../models/GetMarketplaceCategory200Response';
import {
  type GetMarketplaceItem200Response,
  GetMarketplaceItem200ResponseFromJSON,
  GetMarketplaceItem200ResponseToJSON,
} from '../models/GetMarketplaceItem200Response';
import {
  type InstallMarketplaceApp200Response,
  InstallMarketplaceApp200ResponseFromJSON,
  InstallMarketplaceApp200ResponseToJSON,
} from '../models/InstallMarketplaceApp200Response';
import {
  type InstallMarketplaceAppRequest,
  InstallMarketplaceAppRequestFromJSON,
  InstallMarketplaceAppRequestToJSON,
} from '../models/InstallMarketplaceAppRequest';
import {
  type ListInstalledApps200Response,
  ListInstalledApps200ResponseFromJSON,
  ListInstalledApps200ResponseToJSON,
} from '../models/ListInstalledApps200Response';
import {
  type ListMarketplaceApps200Response,
  ListMarketplaceApps200ResponseFromJSON,
  ListMarketplaceApps200ResponseToJSON,
} from '../models/ListMarketplaceApps200Response';
import {
  type ListMarketplaceCategories200Response,
  ListMarketplaceCategories200ResponseFromJSON,
  ListMarketplaceCategories200ResponseToJSON,
} from '../models/ListMarketplaceCategories200Response';
import {
  type ListMarketplaceItems200Response,
  ListMarketplaceItems200ResponseFromJSON,
  ListMarketplaceItems200ResponseToJSON,
} from '../models/ListMarketplaceItems200Response';
import {
  type ListTrendingApps200Response,
  ListTrendingApps200ResponseFromJSON,
  ListTrendingApps200ResponseToJSON,
} from '../models/ListTrendingApps200Response';
import {
  type SearchMarketplaceRequest,
  SearchMarketplaceRequestFromJSON,
  SearchMarketplaceRequestToJSON,
} from '../models/SearchMarketplaceRequest';
import {
  type UninstallMarketplaceApp200Response,
  UninstallMarketplaceApp200ResponseFromJSON,
  UninstallMarketplaceApp200ResponseToJSON,
} from '../models/UninstallMarketplaceApp200Response';

export interface GetMarketplaceAppRequest {
  appId: string;
}

export interface GetMarketplaceCategoryRequest {
  id: string;
}

export interface GetMarketplaceItemRequest {
  id: string;
}

export interface InstallMarketplaceAppOperationRequest {
  appId: string;
  installMarketplaceAppRequest?: InstallMarketplaceAppRequest;
}

export interface ListInstalledAppsRequest {
  limit?: number;
  offset?: number;
}

export interface ListMarketplaceAppsRequest {
  limit?: number;
  offset?: number;
  category?: string;
  search?: string;
}

export interface ListMarketplaceItemsRequest {
  limit?: number;
  offset?: number;
  itemType?: string;
  earnerType?: string;
  categoryId?: string;
  minPrice?: number;
  maxPrice?: number;
  sellerId?: string;
  search?: string;
}

export interface SearchMarketplaceOperationRequest {
  searchMarketplaceRequest?: SearchMarketplaceRequest;
}

export interface UninstallMarketplaceAppRequest {
  appId: string;
}

/**
 *
 */
export class MarketplaceApi extends runtime.BaseAPI {
  /**
   * Creates request options for getCategoryTree without sending the request
   */
  async getCategoryTreeRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v1/marketplace/categories/tree`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns marketplace categories as a hierarchical tree from the collections table. Children are nested category objects of the same shape.
   * Category tree
   */
  async getCategoryTreeRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetCategoryTree200Response>> {
    const requestOptions = await this.getCategoryTreeRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetCategoryTree200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns marketplace categories as a hierarchical tree from the collections table. Children are nested category objects of the same shape.
   * Category tree
   */
  async getCategoryTree(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GetCategoryTree200Response> {
    const response = await this.getCategoryTreeRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getMarketplaceApp without sending the request
   */
  async getMarketplaceAppRequestOpts(
    requestParameters: GetMarketplaceAppRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['appId'] == null) {
      throw new runtime.RequiredError(
        'appId',
        'Required parameter "appId" was null or undefined when calling getMarketplaceApp().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/marketplace/apps/{appId}`;
    urlPath = urlPath.replace('{appId}', encodeURIComponent(String(requestParameters['appId'])));

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Get app details
   */
  async getMarketplaceAppRaw(
    requestParameters: GetMarketplaceAppRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetMarketplaceApp200Response>> {
    const requestOptions = await this.getMarketplaceAppRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetMarketplaceApp200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Get app details
   */
  async getMarketplaceApp(
    requestParameters: GetMarketplaceAppRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GetMarketplaceApp200Response> {
    const response = await this.getMarketplaceAppRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getMarketplaceCategory without sending the request
   */
  async getMarketplaceCategoryRequestOpts(
    requestParameters: GetMarketplaceCategoryRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getMarketplaceCategory().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v1/marketplace/categories/{id}`;
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns a single marketplace category from the collections table.
   * Get category
   */
  async getMarketplaceCategoryRaw(
    requestParameters: GetMarketplaceCategoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetMarketplaceCategory200Response>> {
    const requestOptions = await this.getMarketplaceCategoryRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetMarketplaceCategory200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns a single marketplace category from the collections table.
   * Get category
   */
  async getMarketplaceCategory(
    requestParameters: GetMarketplaceCategoryRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GetMarketplaceCategory200Response> {
    const response = await this.getMarketplaceCategoryRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getMarketplaceItem without sending the request
   */
  async getMarketplaceItemRequestOpts(
    requestParameters: GetMarketplaceItemRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getMarketplaceItem().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v1/marketplace/items/{id}`;
    urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns a single published marketplace item by ID.
   * Get marketplace item
   */
  async getMarketplaceItemRaw(
    requestParameters: GetMarketplaceItemRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetMarketplaceItem200Response>> {
    const requestOptions = await this.getMarketplaceItemRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetMarketplaceItem200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns a single published marketplace item by ID.
   * Get marketplace item
   */
  async getMarketplaceItem(
    requestParameters: GetMarketplaceItemRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GetMarketplaceItem200Response> {
    const response = await this.getMarketplaceItemRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for installMarketplaceApp without sending the request
   */
  async installMarketplaceAppRequestOpts(
    requestParameters: InstallMarketplaceAppOperationRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['appId'] == null) {
      throw new runtime.RequiredError(
        'appId',
        'Required parameter "appId" was null or undefined when calling installMarketplaceApp().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('BearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/marketplace/install/{appId}`;
    urlPath = urlPath.replace('{appId}', encodeURIComponent(String(requestParameters['appId'])));

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: InstallMarketplaceAppRequestToJSON(requestParameters['installMarketplaceAppRequest']),
    };
  }

  /**
   * Install app
   */
  async installMarketplaceAppRaw(
    requestParameters: InstallMarketplaceAppOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<InstallMarketplaceApp200Response>> {
    const requestOptions = await this.installMarketplaceAppRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      InstallMarketplaceApp200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Install app
   */
  async installMarketplaceApp(
    requestParameters: InstallMarketplaceAppOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<InstallMarketplaceApp200Response> {
    const response = await this.installMarketplaceAppRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listFeaturedApps without sending the request
   */
  async listFeaturedAppsRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/marketplace/featured`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns featured approved apps (curated subset of top apps).
   * Featured apps
   */
  async listFeaturedAppsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListTrendingApps200Response>> {
    const requestOptions = await this.listFeaturedAppsRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListTrendingApps200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns featured approved apps (curated subset of top apps).
   * Featured apps
   */
  async listFeaturedApps(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListTrendingApps200Response> {
    const response = await this.listFeaturedAppsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listInstalledApps without sending the request
   */
  async listInstalledAppsRequestOpts(
    requestParameters: ListInstalledAppsRequest
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit'];
    }

    if (requestParameters['offset'] != null) {
      queryParameters['offset'] = requestParameters['offset'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('BearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/marketplace/installed`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns all apps installed by the authenticated user.
   * List installed apps
   */
  async listInstalledAppsRaw(
    requestParameters: ListInstalledAppsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListInstalledApps200Response>> {
    const requestOptions = await this.listInstalledAppsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListInstalledApps200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns all apps installed by the authenticated user.
   * List installed apps
   */
  async listInstalledApps(
    requestParameters: ListInstalledAppsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListInstalledApps200Response> {
    const response = await this.listInstalledAppsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listMarketplaceApps without sending the request
   */
  async listMarketplaceAppsRequestOpts(
    requestParameters: ListMarketplaceAppsRequest
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit'];
    }

    if (requestParameters['offset'] != null) {
      queryParameters['offset'] = requestParameters['offset'];
    }

    if (requestParameters['category'] != null) {
      queryParameters['category'] = requestParameters['category'];
    }

    if (requestParameters['search'] != null) {
      queryParameters['search'] = requestParameters['search'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/marketplace/apps`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns paginated list of approved, active marketplace apps.
   * Browse marketplace apps
   */
  async listMarketplaceAppsRaw(
    requestParameters: ListMarketplaceAppsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListMarketplaceApps200Response>> {
    const requestOptions = await this.listMarketplaceAppsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListMarketplaceApps200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns paginated list of approved, active marketplace apps.
   * Browse marketplace apps
   */
  async listMarketplaceApps(
    requestParameters: ListMarketplaceAppsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListMarketplaceApps200Response> {
    const response = await this.listMarketplaceAppsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listMarketplaceCategories without sending the request
   */
  async listMarketplaceCategoriesRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/marketplace/categories`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns distinct categories from approved apps with their app counts. Note: a second registration of this path exists (no auth, collections-table version) but is shadowed by this route (Express first-match).
   * List app categories
   */
  async listMarketplaceCategoriesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListMarketplaceCategories200Response>> {
    const requestOptions = await this.listMarketplaceCategoriesRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListMarketplaceCategories200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns distinct categories from approved apps with their app counts. Note: a second registration of this path exists (no auth, collections-table version) but is shadowed by this route (Express first-match).
   * List app categories
   */
  async listMarketplaceCategories(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListMarketplaceCategories200Response> {
    const response = await this.listMarketplaceCategoriesRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listMarketplaceItems without sending the request
   */
  async listMarketplaceItemsRequestOpts(
    requestParameters: ListMarketplaceItemsRequest
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit'];
    }

    if (requestParameters['offset'] != null) {
      queryParameters['offset'] = requestParameters['offset'];
    }

    if (requestParameters['itemType'] != null) {
      queryParameters['item_type'] = requestParameters['itemType'];
    }

    if (requestParameters['earnerType'] != null) {
      queryParameters['earner_type'] = requestParameters['earnerType'];
    }

    if (requestParameters['categoryId'] != null) {
      queryParameters['category_id'] = requestParameters['categoryId'];
    }

    if (requestParameters['minPrice'] != null) {
      queryParameters['min_price'] = requestParameters['minPrice'];
    }

    if (requestParameters['maxPrice'] != null) {
      queryParameters['max_price'] = requestParameters['maxPrice'];
    }

    if (requestParameters['sellerId'] != null) {
      queryParameters['seller_id'] = requestParameters['sellerId'];
    }

    if (requestParameters['search'] != null) {
      queryParameters['search'] = requestParameters['search'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v1/marketplace/items`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Public listing of published marketplace items (entry-based). No authentication required.
   * List marketplace items
   */
  async listMarketplaceItemsRaw(
    requestParameters: ListMarketplaceItemsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListMarketplaceItems200Response>> {
    const requestOptions = await this.listMarketplaceItemsRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListMarketplaceItems200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Public listing of published marketplace items (entry-based). No authentication required.
   * List marketplace items
   */
  async listMarketplaceItems(
    requestParameters: ListMarketplaceItemsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListMarketplaceItems200Response> {
    const response = await this.listMarketplaceItemsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listTrendingApps without sending the request
   */
  async listTrendingAppsRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/marketplace/trending`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns approved apps sorted by install count (top 20).
   * Trending apps
   */
  async listTrendingAppsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListTrendingApps200Response>> {
    const requestOptions = await this.listTrendingAppsRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListTrendingApps200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns approved apps sorted by install count (top 20).
   * Trending apps
   */
  async listTrendingApps(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListTrendingApps200Response> {
    const response = await this.listTrendingAppsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for searchMarketplace without sending the request
   */
  async searchMarketplaceRequestOpts(
    requestParameters: SearchMarketplaceOperationRequest
  ): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/api/v1/marketplace/search`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: SearchMarketplaceRequestToJSON(requestParameters['searchMarketplaceRequest']),
    };
  }

  /**
   * Full-text search across marketplace items. No authentication required.
   * Search marketplace
   */
  async searchMarketplaceRaw(
    requestParameters: SearchMarketplaceOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListMarketplaceItems200Response>> {
    const requestOptions = await this.searchMarketplaceRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListMarketplaceItems200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Full-text search across marketplace items. No authentication required.
   * Search marketplace
   */
  async searchMarketplace(
    requestParameters: SearchMarketplaceOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListMarketplaceItems200Response> {
    const response = await this.searchMarketplaceRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for uninstallMarketplaceApp without sending the request
   */
  async uninstallMarketplaceAppRequestOpts(
    requestParameters: UninstallMarketplaceAppRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['appId'] == null) {
      throw new runtime.RequiredError(
        'appId',
        'Required parameter "appId" was null or undefined when calling uninstallMarketplaceApp().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('BearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/marketplace/uninstall/{appId}`;
    urlPath = urlPath.replace('{appId}', encodeURIComponent(String(requestParameters['appId'])));

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Uninstall app
   */
  async uninstallMarketplaceAppRaw(
    requestParameters: UninstallMarketplaceAppRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<UninstallMarketplaceApp200Response>> {
    const requestOptions = await this.uninstallMarketplaceAppRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UninstallMarketplaceApp200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Uninstall app
   */
  async uninstallMarketplaceApp(
    requestParameters: UninstallMarketplaceAppRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<UninstallMarketplaceApp200Response> {
    const response = await this.uninstallMarketplaceAppRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
