/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  type ActivateProfile200Response,
  ActivateProfile200ResponseFromJSON,
  ActivateProfile200ResponseToJSON,
} from '../models/ActivateProfile200Response';
import {
  type GetActiveProfile200Response,
  GetActiveProfile200ResponseFromJSON,
  GetActiveProfile200ResponseToJSON,
} from '../models/GetActiveProfile200Response';
import {
  type ListProfiles200Response,
  ListProfiles200ResponseFromJSON,
  ListProfiles200ResponseToJSON,
} from '../models/ListProfiles200Response';
import {
  type UpdateProfileRequest,
  UpdateProfileRequestFromJSON,
  UpdateProfileRequestToJSON,
} from '../models/UpdateProfileRequest';
import {
  type UpdatedProfile,
  UpdatedProfileFromJSON,
  UpdatedProfileToJSON,
} from '../models/UpdatedProfile';

export interface ActivateProfileRequest {
  profileId: string;
}

export interface UpdateProfileOperationRequest {
  profileId: string;
  updateProfileRequest?: UpdateProfileRequest;
}

/**
 *
 */
export class ProfilesApi extends runtime.BaseAPI {
  /**
   * Creates request options for activateProfile without sending the request
   */
  async activateProfileRequestOpts(
    requestParameters: ActivateProfileRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['profileId'] == null) {
      throw new runtime.RequiredError(
        'profileId',
        'Required parameter "profileId" was null or undefined when calling activateProfile().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/profiles/{profileId}/activate`;
    urlPath = urlPath.replace(
      '{profileId}',
      encodeURIComponent(String(requestParameters['profileId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Switches the active profile to the specified profile.
   * Activate a profile
   */
  async activateProfileRaw(
    requestParameters: ActivateProfileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ActivateProfile200Response>> {
    const requestOptions = await this.activateProfileRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ActivateProfile200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Switches the active profile to the specified profile.
   * Activate a profile
   */
  async activateProfile(
    requestParameters: ActivateProfileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ActivateProfile200Response> {
    const response = await this.activateProfileRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for getActiveProfile without sending the request
   */
  async getActiveProfileRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/profiles/active`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns the default active (non-anonymous) profile for the authenticated API key.
   * Get active profile
   */
  async getActiveProfileRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GetActiveProfile200Response>> {
    const requestOptions = await this.getActiveProfileRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetActiveProfile200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns the default active (non-anonymous) profile for the authenticated API key.
   * Get active profile
   */
  async getActiveProfile(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GetActiveProfile200Response> {
    const response = await this.getActiveProfileRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listProfiles without sending the request
   */
  async listProfilesRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/profiles/available`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns all non-anonymous active profiles for the authenticated API key.
   * List available profiles
   */
  async listProfilesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListProfiles200Response>> {
    const requestOptions = await this.listProfilesRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListProfiles200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns all non-anonymous active profiles for the authenticated API key.
   * List available profiles
   */
  async listProfiles(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListProfiles200Response> {
    const response = await this.listProfilesRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for updateProfile without sending the request
   */
  async updateProfileRequestOpts(
    requestParameters: UpdateProfileOperationRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['profileId'] == null) {
      throw new runtime.RequiredError(
        'profileId',
        'Required parameter "profileId" was null or undefined when calling updateProfile().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/profiles/{profileId}`;
    urlPath = urlPath.replace(
      '{profileId}',
      encodeURIComponent(String(requestParameters['profileId']))
    );

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
      body: UpdateProfileRequestToJSON(requestParameters['updateProfileRequest']),
    };
  }

  /**
   * Update a profile
   */
  async updateProfileRaw(
    requestParameters: UpdateProfileOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<UpdatedProfile>> {
    const requestOptions = await this.updateProfileRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => UpdatedProfileFromJSON(jsonValue));
  }

  /**
   * Update a profile
   */
  async updateProfile(
    requestParameters: UpdateProfileOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<UpdatedProfile> {
    const response = await this.updateProfileRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
