/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  type ListSessions200Response,
  ListSessions200ResponseFromJSON,
  ListSessions200ResponseToJSON,
} from '../models/ListSessions200Response';
import {
  type ListUpcomingSessions200Response,
  ListUpcomingSessions200ResponseFromJSON,
  ListUpcomingSessions200ResponseToJSON,
} from '../models/ListUpcomingSessions200Response';

/**
 *
 */
export class SessionsApi extends runtime.BaseAPI {
  /**
   * Creates request options for listSessions without sending the request
   */
  async listSessionsRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/sessions`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns the user\'s sessions. Sessions feature is not yet implemented — returns empty paginated list.
   * List sessions
   */
  async listSessionsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListSessions200Response>> {
    const requestOptions = await this.listSessionsRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListSessions200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns the user\'s sessions. Sessions feature is not yet implemented — returns empty paginated list.
   * List sessions
   */
  async listSessions(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListSessions200Response> {
    const response = await this.listSessionsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for listUpcomingSessions without sending the request
   */
  async listUpcomingSessionsRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/sessions/upcoming`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns upcoming sessions. Sessions feature is not yet implemented — returns empty list.
   * List upcoming sessions
   */
  async listUpcomingSessionsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListUpcomingSessions200Response>> {
    const requestOptions = await this.listUpcomingSessionsRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListUpcomingSessions200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns upcoming sessions. Sessions feature is not yet implemented — returns empty list.
   * List upcoming sessions
   */
  async listUpcomingSessions(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListUpcomingSessions200Response> {
    const response = await this.listUpcomingSessionsRaw(initOverrides);
    return await response.value();
  }
}
