/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  type ListTeamMembers200Response,
  ListTeamMembers200ResponseFromJSON,
  ListTeamMembers200ResponseToJSON,
} from '../models/ListTeamMembers200Response';

/**
 *
 */
export class TeamApi extends runtime.BaseAPI {
  /**
   * Creates request options for listTeamMembers without sending the request
   */
  async listTeamMembersRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/team/members`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns group memberships for the authenticated user as a flat list of team members.
   * List team members
   */
  async listTeamMembersRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ListTeamMembers200Response>> {
    const requestOptions = await this.listTeamMembersRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ListTeamMembers200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Returns group memberships for the authenticated user as a flat list of team members.
   * List team members
   */
  async listTeamMembers(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ListTeamMembers200Response> {
    const response = await this.listTeamMembersRaw(initOverrides);
    return await response.value();
  }
}
