/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  type CreateUiNotification200Response,
  CreateUiNotification200ResponseFromJSON,
  CreateUiNotification200ResponseToJSON,
} from '../models/CreateUiNotification200Response';

/**
 *
 */
export class UIApi extends runtime.BaseAPI {
  /**
   * Creates request options for createUiNotification without sending the request
   */
  async createUiNotificationRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/ui/notifications`;

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Creates a UI notification for the authenticated user.
   * Create notification
   */
  async createUiNotificationRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<CreateUiNotification200Response>> {
    const requestOptions = await this.createUiNotificationRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateUiNotification200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Creates a UI notification for the authenticated user.
   * Create notification
   */
  async createUiNotification(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<CreateUiNotification200Response> {
    const response = await this.createUiNotificationRaw(initOverrides);
    return await response.value();
  }
}
