/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { type UserMe, UserMeFromJSON, UserMeToJSON } from '../models/UserMe';

/**
 *
 */
export class UserApi extends runtime.BaseAPI {
  /**
   * Creates request options for getCurrentUser without sending the request
   */
  async getCurrentUserRequestOpts(): Promise<runtime.RequestOpts> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('ApiKeyAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/api/v1/user/me`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * Returns the authenticated user\'s active profile and API key metadata.
   * Get current user
   */
  async getCurrentUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<UserMe>> {
    const requestOptions = await this.getCurrentUserRequestOpts();
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => UserMeFromJSON(jsonValue));
  }

  /**
   * Returns the authenticated user\'s active profile and API key metadata.
   * Get current user
   */
  async getCurrentUser(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<UserMe> {
    const response = await this.getCurrentUserRaw(initOverrides);
    return await response.value();
  }
}
