/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivateProfile200ResponseData } from './ActivateProfile200ResponseData';
import {
  ActivateProfile200ResponseDataFromJSON,
  ActivateProfile200ResponseDataFromJSONTyped,
  ActivateProfile200ResponseDataToJSON,
  ActivateProfile200ResponseDataToJSONTyped,
} from './ActivateProfile200ResponseData';

/**
 *
 * @export
 * @interface ActivateProfile200Response
 */
export interface ActivateProfile200Response {
  /**
   *
   * @type {boolean}
   * @memberof ActivateProfile200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ActivateProfile200Response
   */
  success: boolean;
  /**
   *
   * @type {ActivateProfile200ResponseData}
   * @memberof ActivateProfile200Response
   */
  data: ActivateProfile200ResponseData;
}

/**
 * Check if a given object implements the ActivateProfile200Response interface.
 */
export function instanceOfActivateProfile200Response(
  value: object
): value is ActivateProfile200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ActivateProfile200ResponseFromJSON(json: any): ActivateProfile200Response {
  return ActivateProfile200ResponseFromJSONTyped(json, false);
}

export function ActivateProfile200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ActivateProfile200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: ActivateProfile200ResponseDataFromJSON(json['data']),
  };
}

export function ActivateProfile200ResponseToJSON(json: any): ActivateProfile200Response {
  return ActivateProfile200ResponseToJSONTyped(json, false);
}

export function ActivateProfile200ResponseToJSONTyped(
  value?: ActivateProfile200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: ActivateProfile200ResponseDataToJSON(value['data']),
  };
}
