/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ActivateProfile200ResponseData
 */
export interface ActivateProfile200ResponseData {
  /**
   *
   * @type {string}
   * @memberof ActivateProfile200ResponseData
   */
  activeProfile: string;
  /**
   *
   * @type {Date}
   * @memberof ActivateProfile200ResponseData
   */
  switchedAt: Date;
}

/**
 * Check if a given object implements the ActivateProfile200ResponseData interface.
 */
export function instanceOfActivateProfile200ResponseData(
  value: object
): value is ActivateProfile200ResponseData {
  if (!('activeProfile' in value) || value['activeProfile'] === undefined) return false;
  if (!('switchedAt' in value) || value['switchedAt'] === undefined) return false;
  return true;
}

export function ActivateProfile200ResponseDataFromJSON(json: any): ActivateProfile200ResponseData {
  return ActivateProfile200ResponseDataFromJSONTyped(json, false);
}

export function ActivateProfile200ResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ActivateProfile200ResponseData {
  if (json == null) {
    return json;
  }
  return {
    activeProfile: json['activeProfile'],
    switchedAt: new Date(json['switchedAt']),
  };
}

export function ActivateProfile200ResponseDataToJSON(json: any): ActivateProfile200ResponseData {
  return ActivateProfile200ResponseDataToJSONTyped(json, false);
}

export function ActivateProfile200ResponseDataToJSONTyped(
  value?: ActivateProfile200ResponseData | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    activeProfile: value['activeProfile'],
    switchedAt: value['switchedAt'].toISOString(),
  };
}
