/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AnalyticsSummaryDataMetrics
 */
export interface AnalyticsSummaryDataMetrics {
  /**
   *
   * @type {string}
   * @memberof AnalyticsSummaryDataMetrics
   */
  entriesGrowth: string;
  /**
   *
   * @type {string}
   * @memberof AnalyticsSummaryDataMetrics
   */
  responseGrowth: string;
  /**
   *
   * @type {string}
   * @memberof AnalyticsSummaryDataMetrics
   */
  groupActivity: string;
  /**
   *
   * @type {string}
   * @memberof AnalyticsSummaryDataMetrics
   */
  appUsage: string;
}

/**
 * Check if a given object implements the AnalyticsSummaryDataMetrics interface.
 */
export function instanceOfAnalyticsSummaryDataMetrics(
  value: object
): value is AnalyticsSummaryDataMetrics {
  if (!('entriesGrowth' in value) || value['entriesGrowth'] === undefined) return false;
  if (!('responseGrowth' in value) || value['responseGrowth'] === undefined) return false;
  if (!('groupActivity' in value) || value['groupActivity'] === undefined) return false;
  if (!('appUsage' in value) || value['appUsage'] === undefined) return false;
  return true;
}

export function AnalyticsSummaryDataMetricsFromJSON(json: any): AnalyticsSummaryDataMetrics {
  return AnalyticsSummaryDataMetricsFromJSONTyped(json, false);
}

export function AnalyticsSummaryDataMetricsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnalyticsSummaryDataMetrics {
  if (json == null) {
    return json;
  }
  return {
    entriesGrowth: json['entriesGrowth'],
    responseGrowth: json['responseGrowth'],
    groupActivity: json['groupActivity'],
    appUsage: json['appUsage'],
  };
}

export function AnalyticsSummaryDataMetricsToJSON(json: any): AnalyticsSummaryDataMetrics {
  return AnalyticsSummaryDataMetricsToJSONTyped(json, false);
}

export function AnalyticsSummaryDataMetricsToJSONTyped(
  value?: AnalyticsSummaryDataMetrics | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    entriesGrowth: value['entriesGrowth'],
    responseGrowth: value['responseGrowth'],
    groupActivity: value['groupActivity'],
    appUsage: value['appUsage'],
  };
}
