/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalyticsSummaryData } from './AnalyticsSummaryData';
import {
  AnalyticsSummaryDataFromJSON,
  AnalyticsSummaryDataFromJSONTyped,
  AnalyticsSummaryDataToJSON,
  AnalyticsSummaryDataToJSONTyped,
} from './AnalyticsSummaryData';

/**
 *
 * @export
 * @interface AnalyticsSummary
 */
export interface AnalyticsSummary {
  /**
   *
   * @type {boolean}
   * @memberof AnalyticsSummary
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AnalyticsSummary
   */
  success: boolean;
  /**
   *
   * @type {AnalyticsSummaryData}
   * @memberof AnalyticsSummary
   */
  data: AnalyticsSummaryData;
  /**
   *
   * @type {string}
   * @memberof AnalyticsSummary
   */
  message?: string;
}

/**
 * Check if a given object implements the AnalyticsSummary interface.
 */
export function instanceOfAnalyticsSummary(value: object): value is AnalyticsSummary {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function AnalyticsSummaryFromJSON(json: any): AnalyticsSummary {
  return AnalyticsSummaryFromJSONTyped(json, false);
}

export function AnalyticsSummaryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnalyticsSummary {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: AnalyticsSummaryDataFromJSON(json['data']),
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function AnalyticsSummaryToJSON(json: any): AnalyticsSummary {
  return AnalyticsSummaryToJSONTyped(json, false);
}

export function AnalyticsSummaryToJSONTyped(
  value?: AnalyticsSummary | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: AnalyticsSummaryDataToJSON(value['data']),
    message: value['message'],
  };
}
