/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AnalyticsSummaryDataTimeRange
 */
export interface AnalyticsSummaryDataTimeRange {
  /**
   *
   * @type {Date}
   * @memberof AnalyticsSummaryDataTimeRange
   */
  start: Date;
  /**
   *
   * @type {Date}
   * @memberof AnalyticsSummaryDataTimeRange
   */
  end: Date;
}

/**
 * Check if a given object implements the AnalyticsSummaryDataTimeRange interface.
 */
export function instanceOfAnalyticsSummaryDataTimeRange(
  value: object
): value is AnalyticsSummaryDataTimeRange {
  if (!('start' in value) || value['start'] === undefined) return false;
  if (!('end' in value) || value['end'] === undefined) return false;
  return true;
}

export function AnalyticsSummaryDataTimeRangeFromJSON(json: any): AnalyticsSummaryDataTimeRange {
  return AnalyticsSummaryDataTimeRangeFromJSONTyped(json, false);
}

export function AnalyticsSummaryDataTimeRangeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnalyticsSummaryDataTimeRange {
  if (json == null) {
    return json;
  }
  return {
    start: new Date(json['start']),
    end: new Date(json['end']),
  };
}

export function AnalyticsSummaryDataTimeRangeToJSON(json: any): AnalyticsSummaryDataTimeRange {
  return AnalyticsSummaryDataTimeRangeToJSONTyped(json, false);
}

export function AnalyticsSummaryDataTimeRangeToJSONTyped(
  value?: AnalyticsSummaryDataTimeRange | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    start: value['start'].toISOString(),
    end: value['end'].toISOString(),
  };
}
