/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AnalyticsSummaryDataOverview
 */
export interface AnalyticsSummaryDataOverview {
  /**
   *
   * @type {number}
   * @memberof AnalyticsSummaryDataOverview
   */
  totalEntries: number;
  /**
   *
   * @type {number}
   * @memberof AnalyticsSummaryDataOverview
   */
  totalResponses: number;
  /**
   *
   * @type {number}
   * @memberof AnalyticsSummaryDataOverview
   */
  totalGroups: number;
  /**
   *
   * @type {number}
   * @memberof AnalyticsSummaryDataOverview
   */
  installedApps: number;
}

/**
 * Check if a given object implements the AnalyticsSummaryDataOverview interface.
 */
export function instanceOfAnalyticsSummaryDataOverview(
  value: object
): value is AnalyticsSummaryDataOverview {
  if (!('totalEntries' in value) || value['totalEntries'] === undefined) return false;
  if (!('totalResponses' in value) || value['totalResponses'] === undefined) return false;
  if (!('totalGroups' in value) || value['totalGroups'] === undefined) return false;
  if (!('installedApps' in value) || value['installedApps'] === undefined) return false;
  return true;
}

export function AnalyticsSummaryDataOverviewFromJSON(json: any): AnalyticsSummaryDataOverview {
  return AnalyticsSummaryDataOverviewFromJSONTyped(json, false);
}

export function AnalyticsSummaryDataOverviewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnalyticsSummaryDataOverview {
  if (json == null) {
    return json;
  }
  return {
    totalEntries: json['totalEntries'],
    totalResponses: json['totalResponses'],
    totalGroups: json['totalGroups'],
    installedApps: json['installedApps'],
  };
}

export function AnalyticsSummaryDataOverviewToJSON(json: any): AnalyticsSummaryDataOverview {
  return AnalyticsSummaryDataOverviewToJSONTyped(json, false);
}

export function AnalyticsSummaryDataOverviewToJSONTyped(
  value?: AnalyticsSummaryDataOverview | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    totalEntries: value['totalEntries'],
    totalResponses: value['totalResponses'],
    totalGroups: value['totalGroups'],
    installedApps: value['installedApps'],
  };
}
