/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalyticsSummaryDataMetrics } from './AnalyticsSummaryDataMetrics';
import {
  AnalyticsSummaryDataMetricsFromJSON,
  AnalyticsSummaryDataMetricsFromJSONTyped,
  AnalyticsSummaryDataMetricsToJSON,
  AnalyticsSummaryDataMetricsToJSONTyped,
} from './AnalyticsSummaryDataMetrics';
import type { AnalyticsSummaryDataOverview } from './AnalyticsSummaryDataOverview';
import {
  AnalyticsSummaryDataOverviewFromJSON,
  AnalyticsSummaryDataOverviewFromJSONTyped,
  AnalyticsSummaryDataOverviewToJSON,
  AnalyticsSummaryDataOverviewToJSONTyped,
} from './AnalyticsSummaryDataOverview';
import type { AnalyticsSummaryDataTimeRange } from './AnalyticsSummaryDataTimeRange';
import {
  AnalyticsSummaryDataTimeRangeFromJSON,
  AnalyticsSummaryDataTimeRangeFromJSONTyped,
  AnalyticsSummaryDataTimeRangeToJSON,
  AnalyticsSummaryDataTimeRangeToJSONTyped,
} from './AnalyticsSummaryDataTimeRange';

/**
 *
 * @export
 * @interface AnalyticsSummaryData
 */
export interface AnalyticsSummaryData {
  /**
   *
   * @type {AnalyticsSummaryDataOverview}
   * @memberof AnalyticsSummaryData
   */
  overview: AnalyticsSummaryDataOverview;
  /**
   *
   * @type {AnalyticsSummaryDataMetrics}
   * @memberof AnalyticsSummaryData
   */
  metrics: AnalyticsSummaryDataMetrics;
  /**
   *
   * @type {Array<any>}
   * @memberof AnalyticsSummaryData
   */
  recentActivity: Array<any>;
  /**
   *
   * @type {AnalyticsSummaryDataTimeRange}
   * @memberof AnalyticsSummaryData
   */
  timeRange: AnalyticsSummaryDataTimeRange;
}

/**
 * Check if a given object implements the AnalyticsSummaryData interface.
 */
export function instanceOfAnalyticsSummaryData(value: object): value is AnalyticsSummaryData {
  if (!('overview' in value) || value['overview'] === undefined) return false;
  if (!('metrics' in value) || value['metrics'] === undefined) return false;
  if (!('recentActivity' in value) || value['recentActivity'] === undefined) return false;
  if (!('timeRange' in value) || value['timeRange'] === undefined) return false;
  return true;
}

export function AnalyticsSummaryDataFromJSON(json: any): AnalyticsSummaryData {
  return AnalyticsSummaryDataFromJSONTyped(json, false);
}

export function AnalyticsSummaryDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AnalyticsSummaryData {
  if (json == null) {
    return json;
  }
  return {
    overview: AnalyticsSummaryDataOverviewFromJSON(json['overview']),
    metrics: AnalyticsSummaryDataMetricsFromJSON(json['metrics']),
    recentActivity: json['recentActivity'],
    timeRange: AnalyticsSummaryDataTimeRangeFromJSON(json['timeRange']),
  };
}

export function AnalyticsSummaryDataToJSON(json: any): AnalyticsSummaryData {
  return AnalyticsSummaryDataToJSONTyped(json, false);
}

export function AnalyticsSummaryDataToJSONTyped(
  value?: AnalyticsSummaryData | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    overview: AnalyticsSummaryDataOverviewToJSON(value['overview']),
    metrics: AnalyticsSummaryDataMetricsToJSON(value['metrics']),
    recentActivity: value['recentActivity'],
    timeRange: AnalyticsSummaryDataTimeRangeToJSON(value['timeRange']),
  };
}
