/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AuthProfileResponseData
 */
export interface AuthProfileResponseData {
  /**
   *
   * @type {string}
   * @memberof AuthProfileResponseData
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof AuthProfileResponseData
   */
  email: string | null;
  /**
   *
   * @type {string}
   * @memberof AuthProfileResponseData
   */
  displayName: string;
  /**
   *
   * @type {string}
   * @memberof AuthProfileResponseData
   */
  avatar: string | null;
  /**
   *
   * @type {string}
   * @memberof AuthProfileResponseData
   */
  authType: string;
  /**
   *
   * @type {Array<string>}
   * @memberof AuthProfileResponseData
   */
  permissions: Array<string>;
  /**
   *
   * @type {Date}
   * @memberof AuthProfileResponseData
   */
  lastLogin: Date;
  /**
   *
   * @type {string}
   * @memberof AuthProfileResponseData
   */
  accountStatus: string;
  /**
   *
   * @type {boolean}
   * @memberof AuthProfileResponseData
   */
  twoFactorEnabled: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AuthProfileResponseData
   */
  emailVerified: boolean;
}

/**
 * Check if a given object implements the AuthProfileResponseData interface.
 */
export function instanceOfAuthProfileResponseData(value: object): value is AuthProfileResponseData {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('displayName' in value) || value['displayName'] === undefined) return false;
  if (!('avatar' in value) || value['avatar'] === undefined) return false;
  if (!('authType' in value) || value['authType'] === undefined) return false;
  if (!('permissions' in value) || value['permissions'] === undefined) return false;
  if (!('lastLogin' in value) || value['lastLogin'] === undefined) return false;
  if (!('accountStatus' in value) || value['accountStatus'] === undefined) return false;
  if (!('twoFactorEnabled' in value) || value['twoFactorEnabled'] === undefined) return false;
  if (!('emailVerified' in value) || value['emailVerified'] === undefined) return false;
  return true;
}

export function AuthProfileResponseDataFromJSON(json: any): AuthProfileResponseData {
  return AuthProfileResponseDataFromJSONTyped(json, false);
}

export function AuthProfileResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AuthProfileResponseData {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    email: json['email'],
    displayName: json['displayName'],
    avatar: json['avatar'],
    authType: json['authType'],
    permissions: json['permissions'],
    lastLogin: new Date(json['lastLogin']),
    accountStatus: json['accountStatus'],
    twoFactorEnabled: json['twoFactorEnabled'],
    emailVerified: json['emailVerified'],
  };
}

export function AuthProfileResponseDataToJSON(json: any): AuthProfileResponseData {
  return AuthProfileResponseDataToJSONTyped(json, false);
}

export function AuthProfileResponseDataToJSONTyped(
  value?: AuthProfileResponseData | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    email: value['email'],
    displayName: value['displayName'],
    avatar: value['avatar'],
    authType: value['authType'],
    permissions: value['permissions'],
    lastLogin: value['lastLogin'].toISOString(),
    accountStatus: value['accountStatus'],
    twoFactorEnabled: value['twoFactorEnabled'],
    emailVerified: value['emailVerified'],
  };
}
