/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthProfileResponseData } from './AuthProfileResponseData';
import {
  AuthProfileResponseDataFromJSON,
  AuthProfileResponseDataFromJSONTyped,
  AuthProfileResponseDataToJSON,
  AuthProfileResponseDataToJSONTyped,
} from './AuthProfileResponseData';

/**
 *
 * @export
 * @interface AuthProfileResponse
 */
export interface AuthProfileResponse {
  /**
   *
   * @type {boolean}
   * @memberof AuthProfileResponse
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AuthProfileResponse
   */
  success: boolean;
  /**
   *
   * @type {AuthProfileResponseData}
   * @memberof AuthProfileResponse
   */
  data: AuthProfileResponseData;
}

/**
 * Check if a given object implements the AuthProfileResponse interface.
 */
export function instanceOfAuthProfileResponse(value: object): value is AuthProfileResponse {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function AuthProfileResponseFromJSON(json: any): AuthProfileResponse {
  return AuthProfileResponseFromJSONTyped(json, false);
}

export function AuthProfileResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AuthProfileResponse {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: AuthProfileResponseDataFromJSON(json['data']),
  };
}

export function AuthProfileResponseToJSON(json: any): AuthProfileResponse {
  return AuthProfileResponseToJSONTyped(json, false);
}

export function AuthProfileResponseToJSONTyped(
  value?: AuthProfileResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: AuthProfileResponseDataToJSON(value['data']),
  };
}
