/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AuthSessionResponseUser
 */
export interface AuthSessionResponseUser {
  /**
   *
   * @type {string}
   * @memberof AuthSessionResponseUser
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof AuthSessionResponseUser
   */
  email: string | null;
  /**
   *
   * @type {string}
   * @memberof AuthSessionResponseUser
   */
  displayName: string | null;
  /**
   *
   * @type {string}
   * @memberof AuthSessionResponseUser
   */
  username: string | null;
  /**
   *
   * @type {string}
   * @memberof AuthSessionResponseUser
   */
  subscriptionTier: string;
  /**
   *
   * @type {Date}
   * @memberof AuthSessionResponseUser
   */
  createdAt: Date;
}

/**
 * Check if a given object implements the AuthSessionResponseUser interface.
 */
export function instanceOfAuthSessionResponseUser(value: object): value is AuthSessionResponseUser {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('displayName' in value) || value['displayName'] === undefined) return false;
  if (!('username' in value) || value['username'] === undefined) return false;
  if (!('subscriptionTier' in value) || value['subscriptionTier'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  return true;
}

export function AuthSessionResponseUserFromJSON(json: any): AuthSessionResponseUser {
  return AuthSessionResponseUserFromJSONTyped(json, false);
}

export function AuthSessionResponseUserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AuthSessionResponseUser {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    email: json['email'],
    displayName: json['display_name'],
    username: json['username'],
    subscriptionTier: json['subscription_tier'],
    createdAt: new Date(json['created_at']),
  };
}

export function AuthSessionResponseUserToJSON(json: any): AuthSessionResponseUser {
  return AuthSessionResponseUserToJSONTyped(json, false);
}

export function AuthSessionResponseUserToJSONTyped(
  value?: AuthSessionResponseUser | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    email: value['email'],
    display_name: value['displayName'],
    username: value['username'],
    subscription_tier: value['subscriptionTier'],
    created_at: value['createdAt'].toISOString(),
  };
}
