/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthSessionResponseUser } from './AuthSessionResponseUser';
import {
  AuthSessionResponseUserFromJSON,
  AuthSessionResponseUserFromJSONTyped,
  AuthSessionResponseUserToJSON,
  AuthSessionResponseUserToJSONTyped,
} from './AuthSessionResponseUser';

/**
 *
 * @export
 * @interface AuthSessionResponse
 */
export interface AuthSessionResponse {
  /**
   *
   * @type {AuthSessionResponseUser}
   * @memberof AuthSessionResponse
   */
  user: AuthSessionResponseUser;
  /**
   *
   * @type {string}
   * @memberof AuthSessionResponse
   */
  accessToken: string;
  /**
   *
   * @type {string}
   * @memberof AuthSessionResponse
   */
  refreshToken: string;
  /**
   *
   * @type {number}
   * @memberof AuthSessionResponse
   */
  expiresIn: number;
}

/**
 * Check if a given object implements the AuthSessionResponse interface.
 */
export function instanceOfAuthSessionResponse(value: object): value is AuthSessionResponse {
  if (!('user' in value) || value['user'] === undefined) return false;
  if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
  if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
  if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
  return true;
}

export function AuthSessionResponseFromJSON(json: any): AuthSessionResponse {
  return AuthSessionResponseFromJSONTyped(json, false);
}

export function AuthSessionResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AuthSessionResponse {
  if (json == null) {
    return json;
  }
  return {
    user: AuthSessionResponseUserFromJSON(json['user']),
    accessToken: json['access_token'],
    refreshToken: json['refresh_token'],
    expiresIn: json['expires_in'],
  };
}

export function AuthSessionResponseToJSON(json: any): AuthSessionResponse {
  return AuthSessionResponseToJSONTyped(json, false);
}

export function AuthSessionResponseToJSONTyped(
  value?: AuthSessionResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    user: AuthSessionResponseUserToJSON(value['user']),
    access_token: value['accessToken'],
    refresh_token: value['refreshToken'],
    expires_in: value['expiresIn'],
  };
}
