/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Category
 */
export interface Category {
  /**
   *
   * @type {string}
   * @memberof Category
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Category
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Category
   */
  description?: string | null;
  /**
   *
   * @type {string}
   * @memberof Category
   */
  collectionType: string;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof Category
   */
  organizationRules?: { [key: string]: any };
  /**
   *
   * @type {Date}
   * @memberof Category
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof Category
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the Category interface.
 */
export function instanceOfCategory(value: object): value is Category {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('collectionType' in value) || value['collectionType'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  return true;
}

export function CategoryFromJSON(json: any): Category {
  return CategoryFromJSONTyped(json, false);
}

export function CategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Category {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    description: json['description'] == null ? undefined : json['description'],
    collectionType: json['collection_type'],
    organizationRules: json['organization_rules'] == null ? undefined : json['organization_rules'],
    createdAt: new Date(json['created_at']),
    updatedAt: new Date(json['updated_at']),
  };
}

export function CategoryToJSON(json: any): Category {
  return CategoryToJSONTyped(json, false);
}

export function CategoryToJSONTyped(
  value?: Category | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    description: value['description'],
    collection_type: value['collectionType'],
    organization_rules: value['organizationRules'],
    created_at: value['createdAt'].toISOString(),
    updated_at: value['updatedAt'].toISOString(),
  };
}
