/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateDeveloperAppRequest
 */
export interface CreateDeveloperAppRequest {
  /**
   *
   * @type {string}
   * @memberof CreateDeveloperAppRequest
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateDeveloperAppRequest
   */
  slug: string;
  /**
   *
   * @type {string}
   * @memberof CreateDeveloperAppRequest
   */
  tagline?: string;
  /**
   *
   * @type {string}
   * @memberof CreateDeveloperAppRequest
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof CreateDeveloperAppRequest
   */
  category: string;
  /**
   *
   * @type {string}
   * @memberof CreateDeveloperAppRequest
   */
  iconUrl?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof CreateDeveloperAppRequest
   */
  screenshots?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof CreateDeveloperAppRequest
   */
  version?: string;
  /**
   *
   * @type {string}
   * @memberof CreateDeveloperAppRequest
   */
  pricingModel?: string;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof CreateDeveloperAppRequest
   */
  pricingConfig?: { [key: string]: any };
  /**
   *
   * @type {Array<string>}
   * @memberof CreateDeveloperAppRequest
   */
  supportedAudience?: Array<string>;
}

/**
 * Check if a given object implements the CreateDeveloperAppRequest interface.
 */
export function instanceOfCreateDeveloperAppRequest(
  value: object
): value is CreateDeveloperAppRequest {
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('slug' in value) || value['slug'] === undefined) return false;
  if (!('category' in value) || value['category'] === undefined) return false;
  return true;
}

export function CreateDeveloperAppRequestFromJSON(json: any): CreateDeveloperAppRequest {
  return CreateDeveloperAppRequestFromJSONTyped(json, false);
}

export function CreateDeveloperAppRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateDeveloperAppRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
    slug: json['slug'],
    tagline: json['tagline'] == null ? undefined : json['tagline'],
    description: json['description'] == null ? undefined : json['description'],
    category: json['category'],
    iconUrl: json['icon_url'] == null ? undefined : json['icon_url'],
    screenshots: json['screenshots'] == null ? undefined : json['screenshots'],
    version: json['version'] == null ? undefined : json['version'],
    pricingModel: json['pricing_model'] == null ? undefined : json['pricing_model'],
    pricingConfig: json['pricing_config'] == null ? undefined : json['pricing_config'],
    supportedAudience: json['supported_audience'] == null ? undefined : json['supported_audience'],
  };
}

export function CreateDeveloperAppRequestToJSON(json: any): CreateDeveloperAppRequest {
  return CreateDeveloperAppRequestToJSONTyped(json, false);
}

export function CreateDeveloperAppRequestToJSONTyped(
  value?: CreateDeveloperAppRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    slug: value['slug'],
    tagline: value['tagline'],
    description: value['description'],
    category: value['category'],
    icon_url: value['iconUrl'],
    screenshots: value['screenshots'],
    version: value['version'],
    pricing_model: value['pricingModel'],
    pricing_config: value['pricingConfig'],
    supported_audience: value['supportedAudience'],
  };
}
