/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateUiNotification200ResponseData
 */
export interface CreateUiNotification200ResponseData {
  /**
   *
   * @type {string}
   * @memberof CreateUiNotification200ResponseData
   */
  id: string;
}

/**
 * Check if a given object implements the CreateUiNotification200ResponseData interface.
 */
export function instanceOfCreateUiNotification200ResponseData(
  value: object
): value is CreateUiNotification200ResponseData {
  if (!('id' in value) || value['id'] === undefined) return false;
  return true;
}

export function CreateUiNotification200ResponseDataFromJSON(
  json: any
): CreateUiNotification200ResponseData {
  return CreateUiNotification200ResponseDataFromJSONTyped(json, false);
}

export function CreateUiNotification200ResponseDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateUiNotification200ResponseData {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
  };
}

export function CreateUiNotification200ResponseDataToJSON(
  json: any
): CreateUiNotification200ResponseData {
  return CreateUiNotification200ResponseDataToJSONTyped(json, false);
}

export function CreateUiNotification200ResponseDataToJSONTyped(
  value?: CreateUiNotification200ResponseData | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
  };
}
