/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateUiNotification200ResponseData } from './CreateUiNotification200ResponseData';
import {
  CreateUiNotification200ResponseDataFromJSON,
  CreateUiNotification200ResponseDataFromJSONTyped,
  CreateUiNotification200ResponseDataToJSON,
  CreateUiNotification200ResponseDataToJSONTyped,
} from './CreateUiNotification200ResponseData';

/**
 *
 * @export
 * @interface CreateUiNotification200Response
 */
export interface CreateUiNotification200Response {
  /**
   *
   * @type {boolean}
   * @memberof CreateUiNotification200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof CreateUiNotification200Response
   */
  success: boolean;
  /**
   *
   * @type {CreateUiNotification200ResponseData}
   * @memberof CreateUiNotification200Response
   */
  data: CreateUiNotification200ResponseData;
}

/**
 * Check if a given object implements the CreateUiNotification200Response interface.
 */
export function instanceOfCreateUiNotification200Response(
  value: object
): value is CreateUiNotification200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function CreateUiNotification200ResponseFromJSON(
  json: any
): CreateUiNotification200Response {
  return CreateUiNotification200ResponseFromJSONTyped(json, false);
}

export function CreateUiNotification200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateUiNotification200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: CreateUiNotification200ResponseDataFromJSON(json['data']),
  };
}

export function CreateUiNotification200ResponseToJSON(json: any): CreateUiNotification200Response {
  return CreateUiNotification200ResponseToJSONTyped(json, false);
}

export function CreateUiNotification200ResponseToJSONTyped(
  value?: CreateUiNotification200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: CreateUiNotification200ResponseDataToJSON(value['data']),
  };
}
