/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Event } from './Event';
import { EventFromJSON, EventFromJSONTyped, EventToJSON, EventToJSONTyped } from './Event';

/**
 *
 * @export
 * @interface CreateEvent201Response
 */
export interface CreateEvent201Response {
  /**
   *
   * @type {boolean}
   * @memberof CreateEvent201Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof CreateEvent201Response
   */
  success: boolean;
  /**
   *
   * @type {Event}
   * @memberof CreateEvent201Response
   */
  data: Event;
  /**
   *
   * @type {string}
   * @memberof CreateEvent201Response
   */
  message: string;
}

/**
 * Check if a given object implements the CreateEvent201Response interface.
 */
export function instanceOfCreateEvent201Response(value: object): value is CreateEvent201Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function CreateEvent201ResponseFromJSON(json: any): CreateEvent201Response {
  return CreateEvent201ResponseFromJSONTyped(json, false);
}

export function CreateEvent201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateEvent201Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: EventFromJSON(json['data']),
    message: json['message'],
  };
}

export function CreateEvent201ResponseToJSON(json: any): CreateEvent201Response {
  return CreateEvent201ResponseToJSONTyped(json, false);
}

export function CreateEvent201ResponseToJSONTyped(
  value?: CreateEvent201Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: EventToJSON(value['data']),
    message: value['message'],
  };
}
