/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateEventRequest
 */
export interface CreateEventRequest {
  /**
   *
   * @type {string}
   * @memberof CreateEventRequest
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof CreateEventRequest
   */
  description: string;
  /**
   *
   * @type {Date}
   * @memberof CreateEventRequest
   */
  startDate: Date;
  /**
   *
   * @type {Date}
   * @memberof CreateEventRequest
   */
  endDate: Date;
  /**
   *
   * @type {boolean}
   * @memberof CreateEventRequest
   */
  isOnline: boolean;
  /**
   *
   * @type {string}
   * @memberof CreateEventRequest
   */
  category: string;
  /**
   *
   * @type {string}
   * @memberof CreateEventRequest
   */
  location?: string | null;
  /**
   *
   * @type {number}
   * @memberof CreateEventRequest
   */
  maxAttendees?: number | null;
  /**
   *
   * @type {number}
   * @memberof CreateEventRequest
   */
  price?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof CreateEventRequest
   */
  tags?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof CreateEventRequest
   */
  imageUrl?: string | null;
}

/**
 * Check if a given object implements the CreateEventRequest interface.
 */
export function instanceOfCreateEventRequest(value: object): value is CreateEventRequest {
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('startDate' in value) || value['startDate'] === undefined) return false;
  if (!('endDate' in value) || value['endDate'] === undefined) return false;
  if (!('isOnline' in value) || value['isOnline'] === undefined) return false;
  if (!('category' in value) || value['category'] === undefined) return false;
  return true;
}

export function CreateEventRequestFromJSON(json: any): CreateEventRequest {
  return CreateEventRequestFromJSONTyped(json, false);
}

export function CreateEventRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateEventRequest {
  if (json == null) {
    return json;
  }
  return {
    title: json['title'],
    description: json['description'],
    startDate: new Date(json['startDate']),
    endDate: new Date(json['endDate']),
    isOnline: json['isOnline'],
    category: json['category'],
    location: json['location'] == null ? undefined : json['location'],
    maxAttendees: json['maxAttendees'] == null ? undefined : json['maxAttendees'],
    price: json['price'] == null ? undefined : json['price'],
    tags: json['tags'] == null ? undefined : json['tags'],
    imageUrl: json['imageUrl'] == null ? undefined : json['imageUrl'],
  };
}

export function CreateEventRequestToJSON(json: any): CreateEventRequest {
  return CreateEventRequestToJSONTyped(json, false);
}

export function CreateEventRequestToJSONTyped(
  value?: CreateEventRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value['title'],
    description: value['description'],
    startDate: value['startDate'].toISOString(),
    endDate: value['endDate'].toISOString(),
    isOnline: value['isOnline'],
    category: value['category'],
    location: value['location'],
    maxAttendees: value['maxAttendees'],
    price: value['price'],
    tags: value['tags'],
    imageUrl: value['imageUrl'],
  };
}
