/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Entry
 */
export interface Entry {
  /**
   *
   * @type {string}
   * @memberof Entry
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Entry
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof Entry
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof Entry
   */
  profileId: string;
  /**
   *
   * @type {string}
   * @memberof Entry
   */
  audienceType: string;
  /**
   *
   * @type {Date}
   * @memberof Entry
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof Entry
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the Entry interface.
 */
export function instanceOfEntry(value: object): value is Entry {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('profileId' in value) || value['profileId'] === undefined) return false;
  if (!('audienceType' in value) || value['audienceType'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  return true;
}

export function EntryFromJSON(json: any): Entry {
  return EntryFromJSONTyped(json, false);
}

export function EntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Entry {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    title: json['title'],
    content: json['content'],
    profileId: json['profile_id'],
    audienceType: json['audience_type'],
    createdAt: new Date(json['created_at']),
    updatedAt: new Date(json['updated_at']),
  };
}

export function EntryToJSON(json: any): Entry {
  return EntryToJSONTyped(json, false);
}

export function EntryToJSONTyped(value?: Entry | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    title: value['title'],
    content: value['content'],
    profile_id: value['profileId'],
    audience_type: value['audienceType'],
    created_at: value['createdAt'].toISOString(),
    updated_at: value['updatedAt'].toISOString(),
  };
}
