/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Event
 */
export interface Event {
  /**
   *
   * @type {string}
   * @memberof Event
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Event
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof Event
   */
  description: string;
  /**
   *
   * @type {Date}
   * @memberof Event
   */
  startDate: Date;
  /**
   *
   * @type {Date}
   * @memberof Event
   */
  endDate: Date;
  /**
   *
   * @type {string}
   * @memberof Event
   */
  location: string | null;
  /**
   *
   * @type {boolean}
   * @memberof Event
   */
  isOnline: boolean;
  /**
   *
   * @type {string}
   * @memberof Event
   */
  category: string;
  /**
   *
   * @type {string}
   * @memberof Event
   */
  organizer: string;
  /**
   *
   * @type {number}
   * @memberof Event
   */
  maxAttendees: number | null;
  /**
   *
   * @type {number}
   * @memberof Event
   */
  currentAttendees: number | null;
  /**
   *
   * @type {number}
   * @memberof Event
   */
  price: number;
  /**
   *
   * @type {Array<string>}
   * @memberof Event
   */
  tags: Array<string>;
  /**
   *
   * @type {string}
   * @memberof Event
   */
  imageUrl: string | null;
  /**
   *
   * @type {Date}
   * @memberof Event
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof Event
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): value is Event {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('startDate' in value) || value['startDate'] === undefined) return false;
  if (!('endDate' in value) || value['endDate'] === undefined) return false;
  if (!('location' in value) || value['location'] === undefined) return false;
  if (!('isOnline' in value) || value['isOnline'] === undefined) return false;
  if (!('category' in value) || value['category'] === undefined) return false;
  if (!('organizer' in value) || value['organizer'] === undefined) return false;
  if (!('maxAttendees' in value) || value['maxAttendees'] === undefined) return false;
  if (!('currentAttendees' in value) || value['currentAttendees'] === undefined) return false;
  if (!('price' in value) || value['price'] === undefined) return false;
  if (!('tags' in value) || value['tags'] === undefined) return false;
  if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  return true;
}

export function EventFromJSON(json: any): Event {
  return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    title: json['title'],
    description: json['description'],
    startDate: new Date(json['startDate']),
    endDate: new Date(json['endDate']),
    location: json['location'],
    isOnline: json['isOnline'],
    category: json['category'],
    organizer: json['organizer'],
    maxAttendees: json['maxAttendees'],
    currentAttendees: json['currentAttendees'],
    price: json['price'],
    tags: json['tags'],
    imageUrl: json['imageUrl'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
  };
}

export function EventToJSON(json: any): Event {
  return EventToJSONTyped(json, false);
}

export function EventToJSONTyped(value?: Event | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    title: value['title'],
    description: value['description'],
    startDate: value['startDate'].toISOString(),
    endDate: value['endDate'].toISOString(),
    location: value['location'],
    isOnline: value['isOnline'],
    category: value['category'],
    organizer: value['organizer'],
    maxAttendees: value['maxAttendees'],
    currentAttendees: value['currentAttendees'],
    price: value['price'],
    tags: value['tags'],
    imageUrl: value['imageUrl'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
  };
}
