/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProfileSummary } from './ProfileSummary';
import {
  ProfileSummaryFromJSON,
  ProfileSummaryFromJSONTyped,
  ProfileSummaryToJSON,
  ProfileSummaryToJSONTyped,
} from './ProfileSummary';

/**
 *
 * @export
 * @interface GetActiveProfile200Response
 */
export interface GetActiveProfile200Response {
  /**
   *
   * @type {boolean}
   * @memberof GetActiveProfile200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof GetActiveProfile200Response
   */
  success: boolean;
  /**
   *
   * @type {ProfileSummary}
   * @memberof GetActiveProfile200Response
   */
  data: ProfileSummary;
}

/**
 * Check if a given object implements the GetActiveProfile200Response interface.
 */
export function instanceOfGetActiveProfile200Response(
  value: object
): value is GetActiveProfile200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function GetActiveProfile200ResponseFromJSON(json: any): GetActiveProfile200Response {
  return GetActiveProfile200ResponseFromJSONTyped(json, false);
}

export function GetActiveProfile200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetActiveProfile200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: ProfileSummaryFromJSON(json['data']),
  };
}

export function GetActiveProfile200ResponseToJSON(json: any): GetActiveProfile200Response {
  return GetActiveProfile200ResponseToJSONTyped(json, false);
}

export function GetActiveProfile200ResponseToJSONTyped(
  value?: GetActiveProfile200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: ProfileSummaryToJSON(value['data']),
  };
}
