/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetCategoryTree200ResponseDataInner
 */
export interface GetCategoryTree200ResponseDataInner {
  /**
   *
   * @type {string}
   * @memberof GetCategoryTree200ResponseDataInner
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof GetCategoryTree200ResponseDataInner
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof GetCategoryTree200ResponseDataInner
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof GetCategoryTree200ResponseDataInner
   */
  collectionType: string;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof GetCategoryTree200ResponseDataInner
   */
  organizationRules?: { [key: string]: any };
  /**
   *
   * @type {Date}
   * @memberof GetCategoryTree200ResponseDataInner
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof GetCategoryTree200ResponseDataInner
   */
  updatedAt: Date;
  /**
   *
   * @type {Array<{ [key: string]: any; }>}
   * @memberof GetCategoryTree200ResponseDataInner
   */
  children?: Array<{ [key: string]: any }>;
}

/**
 * Check if a given object implements the GetCategoryTree200ResponseDataInner interface.
 */
export function instanceOfGetCategoryTree200ResponseDataInner(
  value: object
): value is GetCategoryTree200ResponseDataInner {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('collectionType' in value) || value['collectionType'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  return true;
}

export function GetCategoryTree200ResponseDataInnerFromJSON(
  json: any
): GetCategoryTree200ResponseDataInner {
  return GetCategoryTree200ResponseDataInnerFromJSONTyped(json, false);
}

export function GetCategoryTree200ResponseDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetCategoryTree200ResponseDataInner {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    description: json['description'] == null ? undefined : json['description'],
    collectionType: json['collection_type'],
    organizationRules: json['organization_rules'] == null ? undefined : json['organization_rules'],
    createdAt: new Date(json['created_at']),
    updatedAt: new Date(json['updated_at']),
    children: json['children'] == null ? undefined : json['children'],
  };
}

export function GetCategoryTree200ResponseDataInnerToJSON(
  json: any
): GetCategoryTree200ResponseDataInner {
  return GetCategoryTree200ResponseDataInnerToJSONTyped(json, false);
}

export function GetCategoryTree200ResponseDataInnerToJSONTyped(
  value?: GetCategoryTree200ResponseDataInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    description: value['description'],
    collection_type: value['collectionType'],
    organization_rules: value['organizationRules'],
    created_at: value['createdAt'].toISOString(),
    updated_at: value['updatedAt'].toISOString(),
    children: value['children'],
  };
}
