/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetCategoryTree200ResponseDataInner } from './GetCategoryTree200ResponseDataInner';
import {
  GetCategoryTree200ResponseDataInnerFromJSON,
  GetCategoryTree200ResponseDataInnerFromJSONTyped,
  GetCategoryTree200ResponseDataInnerToJSON,
  GetCategoryTree200ResponseDataInnerToJSONTyped,
} from './GetCategoryTree200ResponseDataInner';

/**
 *
 * @export
 * @interface GetCategoryTree200Response
 */
export interface GetCategoryTree200Response {
  /**
   *
   * @type {boolean}
   * @memberof GetCategoryTree200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof GetCategoryTree200Response
   */
  success: boolean;
  /**
   *
   * @type {Array<GetCategoryTree200ResponseDataInner>}
   * @memberof GetCategoryTree200Response
   */
  data: Array<GetCategoryTree200ResponseDataInner>;
}

/**
 * Check if a given object implements the GetCategoryTree200Response interface.
 */
export function instanceOfGetCategoryTree200Response(
  value: object
): value is GetCategoryTree200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function GetCategoryTree200ResponseFromJSON(json: any): GetCategoryTree200Response {
  return GetCategoryTree200ResponseFromJSONTyped(json, false);
}

export function GetCategoryTree200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetCategoryTree200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: (json['data'] as Array<any>).map(GetCategoryTree200ResponseDataInnerFromJSON),
  };
}

export function GetCategoryTree200ResponseToJSON(json: any): GetCategoryTree200Response {
  return GetCategoryTree200ResponseToJSONTyped(json, false);
}

export function GetCategoryTree200ResponseToJSONTyped(
  value?: GetCategoryTree200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: (value['data'] as Array<any>).map(GetCategoryTree200ResponseDataInnerToJSON),
  };
}
