/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Event } from './Event';
import { EventFromJSON, EventFromJSONTyped, EventToJSON, EventToJSONTyped } from './Event';

/**
 *
 * @export
 * @interface GetEvent200Response
 */
export interface GetEvent200Response {
  /**
   *
   * @type {boolean}
   * @memberof GetEvent200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof GetEvent200Response
   */
  success: boolean;
  /**
   *
   * @type {Event}
   * @memberof GetEvent200Response
   */
  data: Event;
}

/**
 * Check if a given object implements the GetEvent200Response interface.
 */
export function instanceOfGetEvent200Response(value: object): value is GetEvent200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function GetEvent200ResponseFromJSON(json: any): GetEvent200Response {
  return GetEvent200ResponseFromJSONTyped(json, false);
}

export function GetEvent200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetEvent200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: EventFromJSON(json['data']),
  };
}

export function GetEvent200ResponseToJSON(json: any): GetEvent200Response {
  return GetEvent200ResponseToJSONTyped(json, false);
}

export function GetEvent200ResponseToJSONTyped(
  value?: GetEvent200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: EventToJSON(value['data']),
  };
}
