/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
  CategoryFromJSON,
  CategoryFromJSONTyped,
  CategoryToJSON,
  CategoryToJSONTyped,
} from './Category';

/**
 *
 * @export
 * @interface GetMarketplaceCategory200Response
 */
export interface GetMarketplaceCategory200Response {
  /**
   *
   * @type {boolean}
   * @memberof GetMarketplaceCategory200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof GetMarketplaceCategory200Response
   */
  success: boolean;
  /**
   *
   * @type {Category}
   * @memberof GetMarketplaceCategory200Response
   */
  data: Category;
}

/**
 * Check if a given object implements the GetMarketplaceCategory200Response interface.
 */
export function instanceOfGetMarketplaceCategory200Response(
  value: object
): value is GetMarketplaceCategory200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function GetMarketplaceCategory200ResponseFromJSON(
  json: any
): GetMarketplaceCategory200Response {
  return GetMarketplaceCategory200ResponseFromJSONTyped(json, false);
}

export function GetMarketplaceCategory200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetMarketplaceCategory200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: CategoryFromJSON(json['data']),
  };
}

export function GetMarketplaceCategory200ResponseToJSON(
  json: any
): GetMarketplaceCategory200Response {
  return GetMarketplaceCategory200ResponseToJSONTyped(json, false);
}

export function GetMarketplaceCategory200ResponseToJSONTyped(
  value?: GetMarketplaceCategory200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: CategoryToJSON(value['data']),
  };
}
