/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketplaceApp } from './MarketplaceApp';
import {
  MarketplaceAppFromJSON,
  MarketplaceAppFromJSONTyped,
  MarketplaceAppToJSON,
  MarketplaceAppToJSONTyped,
} from './MarketplaceApp';

/**
 *
 * @export
 * @interface GetMarketplaceApp200Response
 */
export interface GetMarketplaceApp200Response {
  /**
   *
   * @type {boolean}
   * @memberof GetMarketplaceApp200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof GetMarketplaceApp200Response
   */
  success: boolean;
  /**
   *
   * @type {MarketplaceApp}
   * @memberof GetMarketplaceApp200Response
   */
  data: MarketplaceApp;
}

/**
 * Check if a given object implements the GetMarketplaceApp200Response interface.
 */
export function instanceOfGetMarketplaceApp200Response(
  value: object
): value is GetMarketplaceApp200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function GetMarketplaceApp200ResponseFromJSON(json: any): GetMarketplaceApp200Response {
  return GetMarketplaceApp200ResponseFromJSONTyped(json, false);
}

export function GetMarketplaceApp200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetMarketplaceApp200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: MarketplaceAppFromJSON(json['data']),
  };
}

export function GetMarketplaceApp200ResponseToJSON(json: any): GetMarketplaceApp200Response {
  return GetMarketplaceApp200ResponseToJSONTyped(json, false);
}

export function GetMarketplaceApp200ResponseToJSONTyped(
  value?: GetMarketplaceApp200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: MarketplaceAppToJSON(value['data']),
  };
}
