/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketplaceItem } from './MarketplaceItem';
import {
  MarketplaceItemFromJSON,
  MarketplaceItemFromJSONTyped,
  MarketplaceItemToJSON,
  MarketplaceItemToJSONTyped,
} from './MarketplaceItem';

/**
 *
 * @export
 * @interface GetMarketplaceItem200Response
 */
export interface GetMarketplaceItem200Response {
  /**
   *
   * @type {boolean}
   * @memberof GetMarketplaceItem200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof GetMarketplaceItem200Response
   */
  success: boolean;
  /**
   *
   * @type {MarketplaceItem}
   * @memberof GetMarketplaceItem200Response
   */
  data: MarketplaceItem;
}

/**
 * Check if a given object implements the GetMarketplaceItem200Response interface.
 */
export function instanceOfGetMarketplaceItem200Response(
  value: object
): value is GetMarketplaceItem200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function GetMarketplaceItem200ResponseFromJSON(json: any): GetMarketplaceItem200Response {
  return GetMarketplaceItem200ResponseFromJSONTyped(json, false);
}

export function GetMarketplaceItem200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetMarketplaceItem200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: MarketplaceItemFromJSON(json['data']),
  };
}

export function GetMarketplaceItem200ResponseToJSON(json: any): GetMarketplaceItem200Response {
  return GetMarketplaceItem200ResponseToJSONTyped(json, false);
}

export function GetMarketplaceItem200ResponseToJSONTyped(
  value?: GetMarketplaceItem200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: MarketplaceItemToJSON(value['data']),
  };
}
