/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetStorage200Response
 */
export interface GetStorage200Response {
  /**
   *
   * @type {boolean}
   * @memberof GetStorage200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof GetStorage200Response
   */
  success: boolean;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof GetStorage200Response
   */
  data: { [key: string]: any };
}

/**
 * Check if a given object implements the GetStorage200Response interface.
 */
export function instanceOfGetStorage200Response(value: object): value is GetStorage200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function GetStorage200ResponseFromJSON(json: any): GetStorage200Response {
  return GetStorage200ResponseFromJSONTyped(json, false);
}

export function GetStorage200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetStorage200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: json['data'],
  };
}

export function GetStorage200ResponseToJSON(json: any): GetStorage200Response {
  return GetStorage200ResponseToJSONTyped(json, false);
}

export function GetStorage200ResponseToJSONTyped(
  value?: GetStorage200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: value['data'],
  };
}
