/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GroupMember
 */
export interface GroupMember {
  /**
   *
   * @type {string}
   * @memberof GroupMember
   */
  memberId: string;
  /**
   *
   * @type {string}
   * @memberof GroupMember
   */
  displayName: string;
  /**
   *
   * @type {string}
   * @memberof GroupMember
   */
  role: string;
  /**
   *
   * @type {Date}
   * @memberof GroupMember
   */
  joinedAt: Date;
  /**
   *
   * @type {string}
   * @memberof GroupMember
   */
  avatar: string | null;
}

/**
 * Check if a given object implements the GroupMember interface.
 */
export function instanceOfGroupMember(value: object): value is GroupMember {
  if (!('memberId' in value) || value['memberId'] === undefined) return false;
  if (!('displayName' in value) || value['displayName'] === undefined) return false;
  if (!('role' in value) || value['role'] === undefined) return false;
  if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
  if (!('avatar' in value) || value['avatar'] === undefined) return false;
  return true;
}

export function GroupMemberFromJSON(json: any): GroupMember {
  return GroupMemberFromJSONTyped(json, false);
}

export function GroupMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupMember {
  if (json == null) {
    return json;
  }
  return {
    memberId: json['memberId'],
    displayName: json['displayName'],
    role: json['role'],
    joinedAt: new Date(json['joinedAt']),
    avatar: json['avatar'],
  };
}

export function GroupMemberToJSON(json: any): GroupMember {
  return GroupMemberToJSONTyped(json, false);
}

export function GroupMemberToJSONTyped(
  value?: GroupMember | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    memberId: value['memberId'],
    displayName: value['displayName'],
    role: value['role'],
    joinedAt: value['joinedAt'].toISOString(),
    avatar: value['avatar'],
  };
}
