/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GroupSummary
 */
export interface GroupSummary {
  /**
   *
   * @type {string}
   * @memberof GroupSummary
   */
  groupId: string;
  /**
   *
   * @type {string}
   * @memberof GroupSummary
   */
  groupName: string;
  /**
   *
   * @type {number}
   * @memberof GroupSummary
   */
  memberCount: number;
  /**
   *
   * @type {boolean}
   * @memberof GroupSummary
   */
  isActive: boolean;
  /**
   *
   * @type {string}
   * @memberof GroupSummary
   */
  role: string;
  /**
   *
   * @type {string}
   * @memberof GroupSummary
   */
  description: string | null;
  /**
   *
   * @type {string}
   * @memberof GroupSummary
   */
  imageUrl: string | null;
  /**
   *
   * @type {string}
   * @memberof GroupSummary
   */
  externalLink: string | null;
}

/**
 * Check if a given object implements the GroupSummary interface.
 */
export function instanceOfGroupSummary(value: object): value is GroupSummary {
  if (!('groupId' in value) || value['groupId'] === undefined) return false;
  if (!('groupName' in value) || value['groupName'] === undefined) return false;
  if (!('memberCount' in value) || value['memberCount'] === undefined) return false;
  if (!('isActive' in value) || value['isActive'] === undefined) return false;
  if (!('role' in value) || value['role'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
  if (!('externalLink' in value) || value['externalLink'] === undefined) return false;
  return true;
}

export function GroupSummaryFromJSON(json: any): GroupSummary {
  return GroupSummaryFromJSONTyped(json, false);
}

export function GroupSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupSummary {
  if (json == null) {
    return json;
  }
  return {
    groupId: json['groupId'],
    groupName: json['groupName'],
    memberCount: json['memberCount'],
    isActive: json['isActive'],
    role: json['role'],
    description: json['description'],
    imageUrl: json['image_url'],
    externalLink: json['external_link'],
  };
}

export function GroupSummaryToJSON(json: any): GroupSummary {
  return GroupSummaryToJSONTyped(json, false);
}

export function GroupSummaryToJSONTyped(
  value?: GroupSummary | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    groupId: value['groupId'],
    groupName: value['groupName'],
    memberCount: value['memberCount'],
    isActive: value['isActive'],
    role: value['role'],
    description: value['description'],
    image_url: value['imageUrl'],
    external_link: value['externalLink'],
  };
}
