/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InstalledApp } from './InstalledApp';
import {
  InstalledAppFromJSON,
  InstalledAppFromJSONTyped,
  InstalledAppToJSON,
  InstalledAppToJSONTyped,
} from './InstalledApp';

/**
 *
 * @export
 * @interface InstallMarketplaceApp200Response
 */
export interface InstallMarketplaceApp200Response {
  /**
   *
   * @type {boolean}
   * @memberof InstallMarketplaceApp200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof InstallMarketplaceApp200Response
   */
  success: boolean;
  /**
   *
   * @type {InstalledApp}
   * @memberof InstallMarketplaceApp200Response
   */
  data: InstalledApp;
  /**
   *
   * @type {string}
   * @memberof InstallMarketplaceApp200Response
   */
  message: string;
}

/**
 * Check if a given object implements the InstallMarketplaceApp200Response interface.
 */
export function instanceOfInstallMarketplaceApp200Response(
  value: object
): value is InstallMarketplaceApp200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function InstallMarketplaceApp200ResponseFromJSON(
  json: any
): InstallMarketplaceApp200Response {
  return InstallMarketplaceApp200ResponseFromJSONTyped(json, false);
}

export function InstallMarketplaceApp200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InstallMarketplaceApp200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: InstalledAppFromJSON(json['data']),
    message: json['message'],
  };
}

export function InstallMarketplaceApp200ResponseToJSON(
  json: any
): InstallMarketplaceApp200Response {
  return InstallMarketplaceApp200ResponseToJSONTyped(json, false);
}

export function InstallMarketplaceApp200ResponseToJSONTyped(
  value?: InstallMarketplaceApp200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: InstalledAppToJSON(value['data']),
    message: value['message'],
  };
}
