/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface InstallMarketplaceAppRequest
 */
export interface InstallMarketplaceAppRequest {
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof InstallMarketplaceAppRequest
   */
  settings?: { [key: string]: any };
}

/**
 * Check if a given object implements the InstallMarketplaceAppRequest interface.
 */
export function instanceOfInstallMarketplaceAppRequest(
  value: object
): value is InstallMarketplaceAppRequest {
  return true;
}

export function InstallMarketplaceAppRequestFromJSON(json: any): InstallMarketplaceAppRequest {
  return InstallMarketplaceAppRequestFromJSONTyped(json, false);
}

export function InstallMarketplaceAppRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InstallMarketplaceAppRequest {
  if (json == null) {
    return json;
  }
  return {
    settings: json['settings'] == null ? undefined : json['settings'],
  };
}

export function InstallMarketplaceAppRequestToJSON(json: any): InstallMarketplaceAppRequest {
  return InstallMarketplaceAppRequestToJSONTyped(json, false);
}

export function InstallMarketplaceAppRequestToJSONTyped(
  value?: InstallMarketplaceAppRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    settings: value['settings'],
  };
}
