/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketplaceApp } from './MarketplaceApp';
import {
  MarketplaceAppFromJSON,
  MarketplaceAppFromJSONTyped,
  MarketplaceAppToJSON,
  MarketplaceAppToJSONTyped,
} from './MarketplaceApp';

/**
 *
 * @export
 * @interface InstalledApp
 */
export interface InstalledApp {
  /**
   *
   * @type {string}
   * @memberof InstalledApp
   */
  installationId: string;
  /**
   *
   * @type {Date}
   * @memberof InstalledApp
   */
  installedAt: Date;
  /**
   *
   * @type {boolean}
   * @memberof InstalledApp
   */
  isActive: boolean;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof InstalledApp
   */
  settings: { [key: string]: any };
  /**
   *
   * @type {MarketplaceApp}
   * @memberof InstalledApp
   */
  app: MarketplaceApp;
}

/**
 * Check if a given object implements the InstalledApp interface.
 */
export function instanceOfInstalledApp(value: object): value is InstalledApp {
  if (!('installationId' in value) || value['installationId'] === undefined) return false;
  if (!('installedAt' in value) || value['installedAt'] === undefined) return false;
  if (!('isActive' in value) || value['isActive'] === undefined) return false;
  if (!('settings' in value) || value['settings'] === undefined) return false;
  if (!('app' in value) || value['app'] === undefined) return false;
  return true;
}

export function InstalledAppFromJSON(json: any): InstalledApp {
  return InstalledAppFromJSONTyped(json, false);
}

export function InstalledAppFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstalledApp {
  if (json == null) {
    return json;
  }
  return {
    installationId: json['installationId'],
    installedAt: new Date(json['installedAt']),
    isActive: json['isActive'],
    settings: json['settings'],
    app: MarketplaceAppFromJSON(json['app']),
  };
}

export function InstalledAppToJSON(json: any): InstalledApp {
  return InstalledAppToJSONTyped(json, false);
}

export function InstalledAppToJSONTyped(
  value?: InstalledApp | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    installationId: value['installationId'],
    installedAt: value['installedAt'].toISOString(),
    isActive: value['isActive'],
    settings: value['settings'],
    app: MarketplaceAppToJSON(value['app']),
  };
}
