/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Event } from './Event';
import { EventFromJSON, EventFromJSONTyped, EventToJSON, EventToJSONTyped } from './Event';

/**
 *
 * @export
 * @interface ListEvents200Response
 */
export interface ListEvents200Response {
  /**
   *
   * @type {boolean}
   * @memberof ListEvents200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ListEvents200Response
   */
  success: boolean;
  /**
   *
   * @type {Array<Event>}
   * @memberof ListEvents200Response
   */
  data: Array<Event>;
  /**
   *
   * @type {number}
   * @memberof ListEvents200Response
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof ListEvents200Response
   */
  limit: number;
  /**
   *
   * @type {number}
   * @memberof ListEvents200Response
   */
  offset: number;
}

/**
 * Check if a given object implements the ListEvents200Response interface.
 */
export function instanceOfListEvents200Response(value: object): value is ListEvents200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('total' in value) || value['total'] === undefined) return false;
  if (!('limit' in value) || value['limit'] === undefined) return false;
  if (!('offset' in value) || value['offset'] === undefined) return false;
  return true;
}

export function ListEvents200ResponseFromJSON(json: any): ListEvents200Response {
  return ListEvents200ResponseFromJSONTyped(json, false);
}

export function ListEvents200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListEvents200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: (json['data'] as Array<any>).map(EventFromJSON),
    total: json['total'],
    limit: json['limit'],
    offset: json['offset'],
  };
}

export function ListEvents200ResponseToJSON(json: any): ListEvents200Response {
  return ListEvents200ResponseToJSONTyped(json, false);
}

export function ListEvents200ResponseToJSONTyped(
  value?: ListEvents200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: (value['data'] as Array<any>).map(EventToJSON),
    total: value['total'],
    limit: value['limit'],
    offset: value['offset'],
  };
}
