/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ListTeamMembers200ResponseMeta
 */
export interface ListTeamMembers200ResponseMeta {
  /**
   *
   * @type {number}
   * @memberof ListTeamMembers200ResponseMeta
   */
  total: number;
  /**
   *
   * @type {Array<string>}
   * @memberof ListTeamMembers200ResponseMeta
   */
  roles: Array<string>;
}

/**
 * Check if a given object implements the ListTeamMembers200ResponseMeta interface.
 */
export function instanceOfListTeamMembers200ResponseMeta(
  value: object
): value is ListTeamMembers200ResponseMeta {
  if (!('total' in value) || value['total'] === undefined) return false;
  if (!('roles' in value) || value['roles'] === undefined) return false;
  return true;
}

export function ListTeamMembers200ResponseMetaFromJSON(json: any): ListTeamMembers200ResponseMeta {
  return ListTeamMembers200ResponseMetaFromJSONTyped(json, false);
}

export function ListTeamMembers200ResponseMetaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListTeamMembers200ResponseMeta {
  if (json == null) {
    return json;
  }
  return {
    total: json['total'],
    roles: json['roles'],
  };
}

export function ListTeamMembers200ResponseMetaToJSON(json: any): ListTeamMembers200ResponseMeta {
  return ListTeamMembers200ResponseMetaToJSONTyped(json, false);
}

export function ListTeamMembers200ResponseMetaToJSONTyped(
  value?: ListTeamMembers200ResponseMeta | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    total: value['total'],
    roles: value['roles'],
  };
}
