/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListTeamMembers200ResponseMeta } from './ListTeamMembers200ResponseMeta';
import {
  ListTeamMembers200ResponseMetaFromJSON,
  ListTeamMembers200ResponseMetaFromJSONTyped,
  ListTeamMembers200ResponseMetaToJSON,
  ListTeamMembers200ResponseMetaToJSONTyped,
} from './ListTeamMembers200ResponseMeta';
import type { TeamMember } from './TeamMember';
import {
  TeamMemberFromJSON,
  TeamMemberFromJSONTyped,
  TeamMemberToJSON,
  TeamMemberToJSONTyped,
} from './TeamMember';

/**
 *
 * @export
 * @interface ListTeamMembers200Response
 */
export interface ListTeamMembers200Response {
  /**
   *
   * @type {boolean}
   * @memberof ListTeamMembers200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ListTeamMembers200Response
   */
  success: boolean;
  /**
   *
   * @type {Array<TeamMember>}
   * @memberof ListTeamMembers200Response
   */
  data: Array<TeamMember>;
  /**
   *
   * @type {ListTeamMembers200ResponseMeta}
   * @memberof ListTeamMembers200Response
   */
  meta: ListTeamMembers200ResponseMeta;
}

/**
 * Check if a given object implements the ListTeamMembers200Response interface.
 */
export function instanceOfListTeamMembers200Response(
  value: object
): value is ListTeamMembers200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function ListTeamMembers200ResponseFromJSON(json: any): ListTeamMembers200Response {
  return ListTeamMembers200ResponseFromJSONTyped(json, false);
}

export function ListTeamMembers200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListTeamMembers200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: (json['data'] as Array<any>).map(TeamMemberFromJSON),
    meta: ListTeamMembers200ResponseMetaFromJSON(json['meta']),
  };
}

export function ListTeamMembers200ResponseToJSON(json: any): ListTeamMembers200Response {
  return ListTeamMembers200ResponseToJSONTyped(json, false);
}

export function ListTeamMembers200ResponseToJSONTyped(
  value?: ListTeamMembers200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: (value['data'] as Array<any>).map(TeamMemberToJSON),
    meta: ListTeamMembers200ResponseMetaToJSON(value['meta']),
  };
}
