/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ListSessions200ResponseMetaPagination
 */
export interface ListSessions200ResponseMetaPagination {
  /**
   *
   * @type {number}
   * @memberof ListSessions200ResponseMetaPagination
   */
  page: number;
  /**
   *
   * @type {number}
   * @memberof ListSessions200ResponseMetaPagination
   */
  limit: number;
  /**
   *
   * @type {number}
   * @memberof ListSessions200ResponseMetaPagination
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof ListSessions200ResponseMetaPagination
   */
  totalPages: number;
}

/**
 * Check if a given object implements the ListSessions200ResponseMetaPagination interface.
 */
export function instanceOfListSessions200ResponseMetaPagination(
  value: object
): value is ListSessions200ResponseMetaPagination {
  if (!('page' in value) || value['page'] === undefined) return false;
  if (!('limit' in value) || value['limit'] === undefined) return false;
  if (!('total' in value) || value['total'] === undefined) return false;
  if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
  return true;
}

export function ListSessions200ResponseMetaPaginationFromJSON(
  json: any
): ListSessions200ResponseMetaPagination {
  return ListSessions200ResponseMetaPaginationFromJSONTyped(json, false);
}

export function ListSessions200ResponseMetaPaginationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListSessions200ResponseMetaPagination {
  if (json == null) {
    return json;
  }
  return {
    page: json['page'],
    limit: json['limit'],
    total: json['total'],
    totalPages: json['totalPages'],
  };
}

export function ListSessions200ResponseMetaPaginationToJSON(
  json: any
): ListSessions200ResponseMetaPagination {
  return ListSessions200ResponseMetaPaginationToJSONTyped(json, false);
}

export function ListSessions200ResponseMetaPaginationToJSONTyped(
  value?: ListSessions200ResponseMetaPagination | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    page: value['page'],
    limit: value['limit'],
    total: value['total'],
    totalPages: value['totalPages'],
  };
}
