/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupMember } from './GroupMember';
import {
  GroupMemberFromJSON,
  GroupMemberFromJSONTyped,
  GroupMemberToJSON,
  GroupMemberToJSONTyped,
} from './GroupMember';

/**
 *
 * @export
 * @interface ListGroupMembers200Response
 */
export interface ListGroupMembers200Response {
  /**
   *
   * @type {boolean}
   * @memberof ListGroupMembers200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ListGroupMembers200Response
   */
  success: boolean;
  /**
   *
   * @type {Array<GroupMember>}
   * @memberof ListGroupMembers200Response
   */
  data: Array<GroupMember>;
}

/**
 * Check if a given object implements the ListGroupMembers200Response interface.
 */
export function instanceOfListGroupMembers200Response(
  value: object
): value is ListGroupMembers200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ListGroupMembers200ResponseFromJSON(json: any): ListGroupMembers200Response {
  return ListGroupMembers200ResponseFromJSONTyped(json, false);
}

export function ListGroupMembers200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListGroupMembers200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: (json['data'] as Array<any>).map(GroupMemberFromJSON),
  };
}

export function ListGroupMembers200ResponseToJSON(json: any): ListGroupMembers200Response {
  return ListGroupMembers200ResponseToJSONTyped(json, false);
}

export function ListGroupMembers200ResponseToJSONTyped(
  value?: ListGroupMembers200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: (value['data'] as Array<any>).map(GroupMemberToJSON),
  };
}
