/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupSummary } from './GroupSummary';
import {
  GroupSummaryFromJSON,
  GroupSummaryFromJSONTyped,
  GroupSummaryToJSON,
  GroupSummaryToJSONTyped,
} from './GroupSummary';

/**
 *
 * @export
 * @interface ListGroups200Response
 */
export interface ListGroups200Response {
  /**
   *
   * @type {boolean}
   * @memberof ListGroups200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ListGroups200Response
   */
  success: boolean;
  /**
   *
   * @type {Array<GroupSummary>}
   * @memberof ListGroups200Response
   */
  data: Array<GroupSummary>;
}

/**
 * Check if a given object implements the ListGroups200Response interface.
 */
export function instanceOfListGroups200Response(value: object): value is ListGroups200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ListGroups200ResponseFromJSON(json: any): ListGroups200Response {
  return ListGroups200ResponseFromJSONTyped(json, false);
}

export function ListGroups200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListGroups200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: (json['data'] as Array<any>).map(GroupSummaryFromJSON),
  };
}

export function ListGroups200ResponseToJSON(json: any): ListGroups200Response {
  return ListGroups200ResponseToJSONTyped(json, false);
}

export function ListGroups200ResponseToJSONTyped(
  value?: ListGroups200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: (value['data'] as Array<any>).map(GroupSummaryToJSON),
  };
}
