/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketplaceApp } from './MarketplaceApp';
import {
  MarketplaceAppFromJSON,
  MarketplaceAppFromJSONTyped,
  MarketplaceAppToJSON,
  MarketplaceAppToJSONTyped,
} from './MarketplaceApp';
import type { ListSessions200ResponseMeta } from './ListSessions200ResponseMeta';
import {
  ListSessions200ResponseMetaFromJSON,
  ListSessions200ResponseMetaFromJSONTyped,
  ListSessions200ResponseMetaToJSON,
  ListSessions200ResponseMetaToJSONTyped,
} from './ListSessions200ResponseMeta';

/**
 *
 * @export
 * @interface ListMarketplaceApps200Response
 */
export interface ListMarketplaceApps200Response {
  /**
   *
   * @type {boolean}
   * @memberof ListMarketplaceApps200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ListMarketplaceApps200Response
   */
  success: boolean;
  /**
   *
   * @type {Array<MarketplaceApp>}
   * @memberof ListMarketplaceApps200Response
   */
  data: Array<MarketplaceApp>;
  /**
   *
   * @type {ListSessions200ResponseMeta}
   * @memberof ListMarketplaceApps200Response
   */
  meta: ListSessions200ResponseMeta;
}

/**
 * Check if a given object implements the ListMarketplaceApps200Response interface.
 */
export function instanceOfListMarketplaceApps200Response(
  value: object
): value is ListMarketplaceApps200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function ListMarketplaceApps200ResponseFromJSON(json: any): ListMarketplaceApps200Response {
  return ListMarketplaceApps200ResponseFromJSONTyped(json, false);
}

export function ListMarketplaceApps200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListMarketplaceApps200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: (json['data'] as Array<any>).map(MarketplaceAppFromJSON),
    meta: ListSessions200ResponseMetaFromJSON(json['meta']),
  };
}

export function ListMarketplaceApps200ResponseToJSON(json: any): ListMarketplaceApps200Response {
  return ListMarketplaceApps200ResponseToJSONTyped(json, false);
}

export function ListMarketplaceApps200ResponseToJSONTyped(
  value?: ListMarketplaceApps200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: (value['data'] as Array<any>).map(MarketplaceAppToJSON),
    meta: ListSessions200ResponseMetaToJSON(value['meta']),
  };
}
