/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListSessions200ResponseMeta } from './ListSessions200ResponseMeta';
import {
  ListSessions200ResponseMetaFromJSON,
  ListSessions200ResponseMetaFromJSONTyped,
  ListSessions200ResponseMetaToJSON,
  ListSessions200ResponseMetaToJSONTyped,
} from './ListSessions200ResponseMeta';
import type { MarketplaceItem } from './MarketplaceItem';
import {
  MarketplaceItemFromJSON,
  MarketplaceItemFromJSONTyped,
  MarketplaceItemToJSON,
  MarketplaceItemToJSONTyped,
} from './MarketplaceItem';

/**
 *
 * @export
 * @interface ListMarketplaceItems200Response
 */
export interface ListMarketplaceItems200Response {
  /**
   *
   * @type {boolean}
   * @memberof ListMarketplaceItems200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ListMarketplaceItems200Response
   */
  success: boolean;
  /**
   *
   * @type {Array<MarketplaceItem>}
   * @memberof ListMarketplaceItems200Response
   */
  data: Array<MarketplaceItem>;
  /**
   *
   * @type {ListSessions200ResponseMeta}
   * @memberof ListMarketplaceItems200Response
   */
  meta: ListSessions200ResponseMeta;
}

/**
 * Check if a given object implements the ListMarketplaceItems200Response interface.
 */
export function instanceOfListMarketplaceItems200Response(
  value: object
): value is ListMarketplaceItems200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function ListMarketplaceItems200ResponseFromJSON(
  json: any
): ListMarketplaceItems200Response {
  return ListMarketplaceItems200ResponseFromJSONTyped(json, false);
}

export function ListMarketplaceItems200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListMarketplaceItems200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: (json['data'] as Array<any>).map(MarketplaceItemFromJSON),
    meta: ListSessions200ResponseMetaFromJSON(json['meta']),
  };
}

export function ListMarketplaceItems200ResponseToJSON(json: any): ListMarketplaceItems200Response {
  return ListMarketplaceItems200ResponseToJSONTyped(json, false);
}

export function ListMarketplaceItems200ResponseToJSONTyped(
  value?: ListMarketplaceItems200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: (value['data'] as Array<any>).map(MarketplaceItemToJSON),
    meta: ListSessions200ResponseMetaToJSON(value['meta']),
  };
}
