/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListSessions200ResponseMeta } from './ListSessions200ResponseMeta';
import {
  ListSessions200ResponseMetaFromJSON,
  ListSessions200ResponseMetaFromJSONTyped,
  ListSessions200ResponseMetaToJSON,
  ListSessions200ResponseMetaToJSONTyped,
} from './ListSessions200ResponseMeta';
import type { InstalledApp } from './InstalledApp';
import {
  InstalledAppFromJSON,
  InstalledAppFromJSONTyped,
  InstalledAppToJSON,
  InstalledAppToJSONTyped,
} from './InstalledApp';

/**
 *
 * @export
 * @interface ListInstalledApps200Response
 */
export interface ListInstalledApps200Response {
  /**
   *
   * @type {boolean}
   * @memberof ListInstalledApps200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ListInstalledApps200Response
   */
  success: boolean;
  /**
   *
   * @type {Array<InstalledApp>}
   * @memberof ListInstalledApps200Response
   */
  data: Array<InstalledApp>;
  /**
   *
   * @type {ListSessions200ResponseMeta}
   * @memberof ListInstalledApps200Response
   */
  meta: ListSessions200ResponseMeta;
}

/**
 * Check if a given object implements the ListInstalledApps200Response interface.
 */
export function instanceOfListInstalledApps200Response(
  value: object
): value is ListInstalledApps200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function ListInstalledApps200ResponseFromJSON(json: any): ListInstalledApps200Response {
  return ListInstalledApps200ResponseFromJSONTyped(json, false);
}

export function ListInstalledApps200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListInstalledApps200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: (json['data'] as Array<any>).map(InstalledAppFromJSON),
    meta: ListSessions200ResponseMetaFromJSON(json['meta']),
  };
}

export function ListInstalledApps200ResponseToJSON(json: any): ListInstalledApps200Response {
  return ListInstalledApps200ResponseToJSONTyped(json, false);
}

export function ListInstalledApps200ResponseToJSONTyped(
  value?: ListInstalledApps200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: (value['data'] as Array<any>).map(InstalledAppToJSON),
    meta: ListSessions200ResponseMetaToJSON(value['meta']),
  };
}
