/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProfileSummary } from './ProfileSummary';
import {
  ProfileSummaryFromJSON,
  ProfileSummaryFromJSONTyped,
  ProfileSummaryToJSON,
  ProfileSummaryToJSONTyped,
} from './ProfileSummary';

/**
 *
 * @export
 * @interface ListProfiles200Response
 */
export interface ListProfiles200Response {
  /**
   *
   * @type {boolean}
   * @memberof ListProfiles200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ListProfiles200Response
   */
  success: boolean;
  /**
   *
   * @type {Array<ProfileSummary>}
   * @memberof ListProfiles200Response
   */
  data: Array<ProfileSummary>;
}

/**
 * Check if a given object implements the ListProfiles200Response interface.
 */
export function instanceOfListProfiles200Response(value: object): value is ListProfiles200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ListProfiles200ResponseFromJSON(json: any): ListProfiles200Response {
  return ListProfiles200ResponseFromJSONTyped(json, false);
}

export function ListProfiles200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListProfiles200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: (json['data'] as Array<any>).map(ProfileSummaryFromJSON),
  };
}

export function ListProfiles200ResponseToJSON(json: any): ListProfiles200Response {
  return ListProfiles200ResponseToJSONTyped(json, false);
}

export function ListProfiles200ResponseToJSONTyped(
  value?: ListProfiles200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: (value['data'] as Array<any>).map(ProfileSummaryToJSON),
  };
}
