/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketplaceApp } from './MarketplaceApp';
import {
  MarketplaceAppFromJSON,
  MarketplaceAppFromJSONTyped,
  MarketplaceAppToJSON,
  MarketplaceAppToJSONTyped,
} from './MarketplaceApp';

/**
 *
 * @export
 * @interface ListTrendingApps200Response
 */
export interface ListTrendingApps200Response {
  /**
   *
   * @type {boolean}
   * @memberof ListTrendingApps200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ListTrendingApps200Response
   */
  success: boolean;
  /**
   *
   * @type {Array<MarketplaceApp>}
   * @memberof ListTrendingApps200Response
   */
  data: Array<MarketplaceApp>;
}

/**
 * Check if a given object implements the ListTrendingApps200Response interface.
 */
export function instanceOfListTrendingApps200Response(
  value: object
): value is ListTrendingApps200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ListTrendingApps200ResponseFromJSON(json: any): ListTrendingApps200Response {
  return ListTrendingApps200ResponseFromJSONTyped(json, false);
}

export function ListTrendingApps200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListTrendingApps200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: (json['data'] as Array<any>).map(MarketplaceAppFromJSON),
  };
}

export function ListTrendingApps200ResponseToJSON(json: any): ListTrendingApps200Response {
  return ListTrendingApps200ResponseToJSONTyped(json, false);
}

export function ListTrendingApps200ResponseToJSONTyped(
  value?: ListTrendingApps200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: (value['data'] as Array<any>).map(MarketplaceAppToJSON),
  };
}
