/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ListMarketplaceCategories200ResponseDataInner
 */
export interface ListMarketplaceCategories200ResponseDataInner {
  /**
   *
   * @type {string}
   * @memberof ListMarketplaceCategories200ResponseDataInner
   */
  category: string;
  /**
   *
   * @type {number}
   * @memberof ListMarketplaceCategories200ResponseDataInner
   */
  count: number;
}

/**
 * Check if a given object implements the ListMarketplaceCategories200ResponseDataInner interface.
 */
export function instanceOfListMarketplaceCategories200ResponseDataInner(
  value: object
): value is ListMarketplaceCategories200ResponseDataInner {
  if (!('category' in value) || value['category'] === undefined) return false;
  if (!('count' in value) || value['count'] === undefined) return false;
  return true;
}

export function ListMarketplaceCategories200ResponseDataInnerFromJSON(
  json: any
): ListMarketplaceCategories200ResponseDataInner {
  return ListMarketplaceCategories200ResponseDataInnerFromJSONTyped(json, false);
}

export function ListMarketplaceCategories200ResponseDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListMarketplaceCategories200ResponseDataInner {
  if (json == null) {
    return json;
  }
  return {
    category: json['category'],
    count: json['count'],
  };
}

export function ListMarketplaceCategories200ResponseDataInnerToJSON(
  json: any
): ListMarketplaceCategories200ResponseDataInner {
  return ListMarketplaceCategories200ResponseDataInnerToJSONTyped(json, false);
}

export function ListMarketplaceCategories200ResponseDataInnerToJSONTyped(
  value?: ListMarketplaceCategories200ResponseDataInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    category: value['category'],
    count: value['count'],
  };
}
