/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Entry } from './Entry';
import { EntryFromJSON, EntryFromJSONTyped, EntryToJSON, EntryToJSONTyped } from './Entry';
import type { ListSessions200ResponseMeta } from './ListSessions200ResponseMeta';
import {
  ListSessions200ResponseMetaFromJSON,
  ListSessions200ResponseMetaFromJSONTyped,
  ListSessions200ResponseMetaToJSON,
  ListSessions200ResponseMetaToJSONTyped,
} from './ListSessions200ResponseMeta';

/**
 *
 * @export
 * @interface ListEntries200Response
 */
export interface ListEntries200Response {
  /**
   *
   * @type {boolean}
   * @memberof ListEntries200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ListEntries200Response
   */
  success: boolean;
  /**
   *
   * @type {Array<Entry>}
   * @memberof ListEntries200Response
   */
  data: Array<Entry>;
  /**
   *
   * @type {ListSessions200ResponseMeta}
   * @memberof ListEntries200Response
   */
  meta: ListSessions200ResponseMeta;
}

/**
 * Check if a given object implements the ListEntries200Response interface.
 */
export function instanceOfListEntries200Response(value: object): value is ListEntries200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function ListEntries200ResponseFromJSON(json: any): ListEntries200Response {
  return ListEntries200ResponseFromJSONTyped(json, false);
}

export function ListEntries200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListEntries200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: (json['data'] as Array<any>).map(EntryFromJSON),
    meta: ListSessions200ResponseMetaFromJSON(json['meta']),
  };
}

export function ListEntries200ResponseToJSON(json: any): ListEntries200Response {
  return ListEntries200ResponseToJSONTyped(json, false);
}

export function ListEntries200ResponseToJSONTyped(
  value?: ListEntries200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: (value['data'] as Array<any>).map(EntryToJSON),
    meta: ListSessions200ResponseMetaToJSON(value['meta']),
  };
}
