/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ListUpcomingSessions200Response
 */
export interface ListUpcomingSessions200Response {
  /**
   *
   * @type {boolean}
   * @memberof ListUpcomingSessions200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ListUpcomingSessions200Response
   */
  success: boolean;
  /**
   *
   * @type {Array<any>}
   * @memberof ListUpcomingSessions200Response
   */
  data: Array<any>;
  /**
   *
   * @type {string}
   * @memberof ListUpcomingSessions200Response
   */
  message?: string;
}

/**
 * Check if a given object implements the ListUpcomingSessions200Response interface.
 */
export function instanceOfListUpcomingSessions200Response(
  value: object
): value is ListUpcomingSessions200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ListUpcomingSessions200ResponseFromJSON(
  json: any
): ListUpcomingSessions200Response {
  return ListUpcomingSessions200ResponseFromJSONTyped(json, false);
}

export function ListUpcomingSessions200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListUpcomingSessions200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: json['data'],
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function ListUpcomingSessions200ResponseToJSON(json: any): ListUpcomingSessions200Response {
  return ListUpcomingSessions200ResponseToJSONTyped(json, false);
}

export function ListUpcomingSessions200ResponseToJSONTyped(
  value?: ListUpcomingSessions200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: value['data'],
    message: value['message'],
  };
}
