/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListSessions200ResponseMetaPagination } from './ListSessions200ResponseMetaPagination';
import {
  ListSessions200ResponseMetaPaginationFromJSON,
  ListSessions200ResponseMetaPaginationFromJSONTyped,
  ListSessions200ResponseMetaPaginationToJSON,
  ListSessions200ResponseMetaPaginationToJSONTyped,
} from './ListSessions200ResponseMetaPagination';

/**
 *
 * @export
 * @interface ListSessions200ResponseMeta
 */
export interface ListSessions200ResponseMeta {
  /**
   *
   * @type {ListSessions200ResponseMetaPagination}
   * @memberof ListSessions200ResponseMeta
   */
  pagination: ListSessions200ResponseMetaPagination;
}

/**
 * Check if a given object implements the ListSessions200ResponseMeta interface.
 */
export function instanceOfListSessions200ResponseMeta(
  value: object
): value is ListSessions200ResponseMeta {
  if (!('pagination' in value) || value['pagination'] === undefined) return false;
  return true;
}

export function ListSessions200ResponseMetaFromJSON(json: any): ListSessions200ResponseMeta {
  return ListSessions200ResponseMetaFromJSONTyped(json, false);
}

export function ListSessions200ResponseMetaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListSessions200ResponseMeta {
  if (json == null) {
    return json;
  }
  return {
    pagination: ListSessions200ResponseMetaPaginationFromJSON(json['pagination']),
  };
}

export function ListSessions200ResponseMetaToJSON(json: any): ListSessions200ResponseMeta {
  return ListSessions200ResponseMetaToJSONTyped(json, false);
}

export function ListSessions200ResponseMetaToJSONTyped(
  value?: ListSessions200ResponseMeta | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    pagination: ListSessions200ResponseMetaPaginationToJSON(value['pagination']),
  };
}
