/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListMarketplaceCategories200ResponseDataInner } from './ListMarketplaceCategories200ResponseDataInner';
import {
  ListMarketplaceCategories200ResponseDataInnerFromJSON,
  ListMarketplaceCategories200ResponseDataInnerFromJSONTyped,
  ListMarketplaceCategories200ResponseDataInnerToJSON,
  ListMarketplaceCategories200ResponseDataInnerToJSONTyped,
} from './ListMarketplaceCategories200ResponseDataInner';

/**
 *
 * @export
 * @interface ListMarketplaceCategories200Response
 */
export interface ListMarketplaceCategories200Response {
  /**
   *
   * @type {boolean}
   * @memberof ListMarketplaceCategories200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ListMarketplaceCategories200Response
   */
  success: boolean;
  /**
   *
   * @type {Array<ListMarketplaceCategories200ResponseDataInner>}
   * @memberof ListMarketplaceCategories200Response
   */
  data: Array<ListMarketplaceCategories200ResponseDataInner>;
}

/**
 * Check if a given object implements the ListMarketplaceCategories200Response interface.
 */
export function instanceOfListMarketplaceCategories200Response(
  value: object
): value is ListMarketplaceCategories200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function ListMarketplaceCategories200ResponseFromJSON(
  json: any
): ListMarketplaceCategories200Response {
  return ListMarketplaceCategories200ResponseFromJSONTyped(json, false);
}

export function ListMarketplaceCategories200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListMarketplaceCategories200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: (json['data'] as Array<any>).map(ListMarketplaceCategories200ResponseDataInnerFromJSON),
  };
}

export function ListMarketplaceCategories200ResponseToJSON(
  json: any
): ListMarketplaceCategories200Response {
  return ListMarketplaceCategories200ResponseToJSONTyped(json, false);
}

export function ListMarketplaceCategories200ResponseToJSONTyped(
  value?: ListMarketplaceCategories200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: (value['data'] as Array<any>).map(ListMarketplaceCategories200ResponseDataInnerToJSON),
  };
}
