/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListSessions200ResponseMeta } from './ListSessions200ResponseMeta';
import {
  ListSessions200ResponseMetaFromJSON,
  ListSessions200ResponseMetaFromJSONTyped,
  ListSessions200ResponseMetaToJSON,
  ListSessions200ResponseMetaToJSONTyped,
} from './ListSessions200ResponseMeta';

/**
 *
 * @export
 * @interface ListSessions200Response
 */
export interface ListSessions200Response {
  /**
   *
   * @type {boolean}
   * @memberof ListSessions200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof ListSessions200Response
   */
  success: boolean;
  /**
   *
   * @type {Array<any>}
   * @memberof ListSessions200Response
   */
  data: Array<any>;
  /**
   *
   * @type {ListSessions200ResponseMeta}
   * @memberof ListSessions200Response
   */
  meta: ListSessions200ResponseMeta;
  /**
   *
   * @type {string}
   * @memberof ListSessions200Response
   */
  message?: string;
}

/**
 * Check if a given object implements the ListSessions200Response interface.
 */
export function instanceOfListSessions200Response(value: object): value is ListSessions200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('meta' in value) || value['meta'] === undefined) return false;
  return true;
}

export function ListSessions200ResponseFromJSON(json: any): ListSessions200Response {
  return ListSessions200ResponseFromJSONTyped(json, false);
}

export function ListSessions200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ListSessions200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: json['data'],
    meta: ListSessions200ResponseMetaFromJSON(json['meta']),
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function ListSessions200ResponseToJSON(json: any): ListSessions200Response {
  return ListSessions200ResponseToJSONTyped(json, false);
}

export function ListSessions200ResponseToJSONTyped(
  value?: ListSessions200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: value['data'],
    meta: ListSessions200ResponseMetaToJSON(value['meta']),
    message: value['message'],
  };
}
