/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MarketplaceItem
 */
export interface MarketplaceItem {
  /**
   *
   * @type {string}
   * @memberof MarketplaceItem
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof MarketplaceItem
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof MarketplaceItem
   */
  content?: string | null;
  /**
   *
   * @type {string}
   * @memberof MarketplaceItem
   */
  profileId: string;
  /**
   *
   * @type {string}
   * @memberof MarketplaceItem
   */
  entryType: string;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof MarketplaceItem
   */
  marketplaceMetadata?: { [key: string]: any };
  /**
   *
   * @type {Date}
   * @memberof MarketplaceItem
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof MarketplaceItem
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the MarketplaceItem interface.
 */
export function instanceOfMarketplaceItem(value: object): value is MarketplaceItem {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('profileId' in value) || value['profileId'] === undefined) return false;
  if (!('entryType' in value) || value['entryType'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  return true;
}

export function MarketplaceItemFromJSON(json: any): MarketplaceItem {
  return MarketplaceItemFromJSONTyped(json, false);
}

export function MarketplaceItemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MarketplaceItem {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    title: json['title'],
    content: json['content'] == null ? undefined : json['content'],
    profileId: json['profile_id'],
    entryType: json['entry_type'],
    marketplaceMetadata:
      json['marketplace_metadata'] == null ? undefined : json['marketplace_metadata'],
    createdAt: new Date(json['created_at']),
    updatedAt: new Date(json['updated_at']),
  };
}

export function MarketplaceItemToJSON(json: any): MarketplaceItem {
  return MarketplaceItemToJSONTyped(json, false);
}

export function MarketplaceItemToJSONTyped(
  value?: MarketplaceItem | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    title: value['title'],
    content: value['content'],
    profile_id: value['profileId'],
    entry_type: value['entryType'],
    marketplace_metadata: value['marketplaceMetadata'],
    created_at: value['createdAt'].toISOString(),
    updated_at: value['updatedAt'].toISOString(),
  };
}
