/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MarketplaceApp
 */
export interface MarketplaceApp {
  /**
   *
   * @type {string}
   * @memberof MarketplaceApp
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof MarketplaceApp
   */
  externalId?: string;
  /**
   *
   * @type {string}
   * @memberof MarketplaceApp
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof MarketplaceApp
   */
  slug: string;
  /**
   *
   * @type {string}
   * @memberof MarketplaceApp
   */
  tagline?: string | null;
  /**
   *
   * @type {string}
   * @memberof MarketplaceApp
   */
  description?: string | null;
  /**
   *
   * @type {string}
   * @memberof MarketplaceApp
   */
  category: string;
  /**
   *
   * @type {string}
   * @memberof MarketplaceApp
   */
  iconUrl?: string | null;
  /**
   *
   * @type {Array<string>}
   * @memberof MarketplaceApp
   */
  screenshots?: Array<string> | null;
  /**
   *
   * @type {string}
   * @memberof MarketplaceApp
   */
  version: string;
  /**
   *
   * @type {string}
   * @memberof MarketplaceApp
   */
  pricingModel: string;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof MarketplaceApp
   */
  pricingConfig?: { [key: string]: any };
  /**
   *
   * @type {number}
   * @memberof MarketplaceApp
   */
  installCount: number;
  /**
   *
   * @type {string}
   * @memberof MarketplaceApp
   */
  developerId: string;
  /**
   *
   * @type {string}
   * @memberof MarketplaceApp
   */
  developerName: string;
  /**
   *
   * @type {MarketplaceAppStatusEnum}
   * @memberof MarketplaceApp
   */
  status: MarketplaceAppStatusEnum;
  /**
   *
   * @type {boolean}
   * @memberof MarketplaceApp
   */
  isActive: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof MarketplaceApp
   */
  supportedAudience?: Array<string> | null;
  /**
   *
   * @type {Date}
   * @memberof MarketplaceApp
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof MarketplaceApp
   */
  updatedAt: Date;
}

/**
 * @export
 */
export const MarketplaceAppStatusEnum = {
  Draft: 'draft',
  PendingReview: 'pending_review',
  Approved: 'approved',
  Rejected: 'rejected',
} as const;
export type MarketplaceAppStatusEnum =
  (typeof MarketplaceAppStatusEnum)[keyof typeof MarketplaceAppStatusEnum];

/**
 * Check if a given object implements the MarketplaceApp interface.
 */
export function instanceOfMarketplaceApp(value: object): value is MarketplaceApp {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('slug' in value) || value['slug'] === undefined) return false;
  if (!('category' in value) || value['category'] === undefined) return false;
  if (!('version' in value) || value['version'] === undefined) return false;
  if (!('pricingModel' in value) || value['pricingModel'] === undefined) return false;
  if (!('installCount' in value) || value['installCount'] === undefined) return false;
  if (!('developerId' in value) || value['developerId'] === undefined) return false;
  if (!('developerName' in value) || value['developerName'] === undefined) return false;
  if (!('status' in value) || value['status'] === undefined) return false;
  if (!('isActive' in value) || value['isActive'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  return true;
}

export function MarketplaceAppFromJSON(json: any): MarketplaceApp {
  return MarketplaceAppFromJSONTyped(json, false);
}

export function MarketplaceAppFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): MarketplaceApp {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    externalId: json['external_id'] == null ? undefined : json['external_id'],
    name: json['name'],
    slug: json['slug'],
    tagline: json['tagline'] == null ? undefined : json['tagline'],
    description: json['description'] == null ? undefined : json['description'],
    category: json['category'],
    iconUrl: json['icon_url'] == null ? undefined : json['icon_url'],
    screenshots: json['screenshots'] == null ? undefined : json['screenshots'],
    version: json['version'],
    pricingModel: json['pricing_model'],
    pricingConfig: json['pricing_config'] == null ? undefined : json['pricing_config'],
    installCount: json['install_count'],
    developerId: json['developer_id'],
    developerName: json['developer_name'],
    status: json['status'],
    isActive: json['is_active'],
    supportedAudience: json['supported_audience'] == null ? undefined : json['supported_audience'],
    createdAt: new Date(json['created_at']),
    updatedAt: new Date(json['updated_at']),
  };
}

export function MarketplaceAppToJSON(json: any): MarketplaceApp {
  return MarketplaceAppToJSONTyped(json, false);
}

export function MarketplaceAppToJSONTyped(
  value?: MarketplaceApp | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    external_id: value['externalId'],
    name: value['name'],
    slug: value['slug'],
    tagline: value['tagline'],
    description: value['description'],
    category: value['category'],
    icon_url: value['iconUrl'],
    screenshots: value['screenshots'],
    version: value['version'],
    pricing_model: value['pricingModel'],
    pricing_config: value['pricingConfig'],
    install_count: value['installCount'],
    developer_id: value['developerId'],
    developer_name: value['developerName'],
    status: value['status'],
    is_active: value['isActive'],
    supported_audience: value['supportedAudience'],
    created_at: value['createdAt'].toISOString(),
    updated_at: value['updatedAt'].toISOString(),
  };
}
