/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PatchAuthProfileRequest
 */
export interface PatchAuthProfileRequest {
  /**
   *
   * @type {string}
   * @memberof PatchAuthProfileRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof PatchAuthProfileRequest
   */
  bio?: string;
  /**
   *
   * @type {string}
   * @memberof PatchAuthProfileRequest
   */
  avatarUrl?: string;
  /**
   *
   * @type {string}
   * @memberof PatchAuthProfileRequest
   */
  location?: string;
  /**
   *
   * @type {string}
   * @memberof PatchAuthProfileRequest
   */
  websiteUrl?: string;
}

/**
 * Check if a given object implements the PatchAuthProfileRequest interface.
 */
export function instanceOfPatchAuthProfileRequest(value: object): value is PatchAuthProfileRequest {
  return true;
}

export function PatchAuthProfileRequestFromJSON(json: any): PatchAuthProfileRequest {
  return PatchAuthProfileRequestFromJSONTyped(json, false);
}

export function PatchAuthProfileRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PatchAuthProfileRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    bio: json['bio'] == null ? undefined : json['bio'],
    avatarUrl: json['avatar_url'] == null ? undefined : json['avatar_url'],
    location: json['location'] == null ? undefined : json['location'],
    websiteUrl: json['website_url'] == null ? undefined : json['website_url'],
  };
}

export function PatchAuthProfileRequestToJSON(json: any): PatchAuthProfileRequest {
  return PatchAuthProfileRequestToJSONTyped(json, false);
}

export function PatchAuthProfileRequestToJSONTyped(
  value?: PatchAuthProfileRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    bio: value['bio'],
    avatar_url: value['avatarUrl'],
    location: value['location'],
    website_url: value['websiteUrl'],
  };
}
