/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ProfileSummary
 */
export interface ProfileSummary {
  /**
   *
   * @type {string}
   * @memberof ProfileSummary
   */
  profileId: string;
  /**
   *
   * @type {string}
   * @memberof ProfileSummary
   */
  profileName: string;
  /**
   *
   * @type {boolean}
   * @memberof ProfileSummary
   */
  isActive: boolean;
  /**
   *
   * @type {string}
   * @memberof ProfileSummary
   */
  avatar: string | null;
  /**
   *
   * @type {boolean}
   * @memberof ProfileSummary
   */
  isDefault: boolean;
}

/**
 * Check if a given object implements the ProfileSummary interface.
 */
export function instanceOfProfileSummary(value: object): value is ProfileSummary {
  if (!('profileId' in value) || value['profileId'] === undefined) return false;
  if (!('profileName' in value) || value['profileName'] === undefined) return false;
  if (!('isActive' in value) || value['isActive'] === undefined) return false;
  if (!('avatar' in value) || value['avatar'] === undefined) return false;
  if (!('isDefault' in value) || value['isDefault'] === undefined) return false;
  return true;
}

export function ProfileSummaryFromJSON(json: any): ProfileSummary {
  return ProfileSummaryFromJSONTyped(json, false);
}

export function ProfileSummaryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ProfileSummary {
  if (json == null) {
    return json;
  }
  return {
    profileId: json['profileId'],
    profileName: json['profileName'],
    isActive: json['isActive'],
    avatar: json['avatar'],
    isDefault: json['isDefault'],
  };
}

export function ProfileSummaryToJSON(json: any): ProfileSummary {
  return ProfileSummaryToJSONTyped(json, false);
}

export function ProfileSummaryToJSONTyped(
  value?: ProfileSummary | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    profileId: value['profileId'],
    profileName: value['profileName'],
    isActive: value['isActive'],
    avatar: value['avatar'],
    isDefault: value['isDefault'],
  };
}
