/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PutAuthProfileRequest
 */
export interface PutAuthProfileRequest {
  /**
   *
   * @type {string}
   * @memberof PutAuthProfileRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof PutAuthProfileRequest
   */
  bio?: string;
  /**
   *
   * @type {string}
   * @memberof PutAuthProfileRequest
   */
  avatarUrl?: string;
  /**
   *
   * @type {string}
   * @memberof PutAuthProfileRequest
   */
  location?: string;
  /**
   *
   * @type {string}
   * @memberof PutAuthProfileRequest
   */
  websiteUrl?: string;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof PutAuthProfileRequest
   */
  preferences?: { [key: string]: any };
  /**
   *
   * @type {number}
   * @memberof PutAuthProfileRequest
   */
  dataRetentionDays?: number;
}

/**
 * Check if a given object implements the PutAuthProfileRequest interface.
 */
export function instanceOfPutAuthProfileRequest(value: object): value is PutAuthProfileRequest {
  return true;
}

export function PutAuthProfileRequestFromJSON(json: any): PutAuthProfileRequest {
  return PutAuthProfileRequestFromJSONTyped(json, false);
}

export function PutAuthProfileRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PutAuthProfileRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    bio: json['bio'] == null ? undefined : json['bio'],
    avatarUrl: json['avatar_url'] == null ? undefined : json['avatar_url'],
    location: json['location'] == null ? undefined : json['location'],
    websiteUrl: json['website_url'] == null ? undefined : json['website_url'],
    preferences: json['preferences'] == null ? undefined : json['preferences'],
    dataRetentionDays:
      json['data_retention_days'] == null ? undefined : json['data_retention_days'],
  };
}

export function PutAuthProfileRequestToJSON(json: any): PutAuthProfileRequest {
  return PutAuthProfileRequestToJSONTyped(json, false);
}

export function PutAuthProfileRequestToJSONTyped(
  value?: PutAuthProfileRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    bio: value['bio'],
    avatar_url: value['avatarUrl'],
    location: value['location'],
    website_url: value['websiteUrl'],
    preferences: value['preferences'],
    data_retention_days: value['dataRetentionDays'],
  };
}
