/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RawProfileResponse
 */
export interface RawProfileResponse {
  /**
   *
   * @type {string}
   * @memberof RawProfileResponse
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof RawProfileResponse
   */
  displayName: string | null;
  /**
   *
   * @type {string}
   * @memberof RawProfileResponse
   */
  username: string | null;
  /**
   *
   * @type {string}
   * @memberof RawProfileResponse
   */
  bio: string | null;
  /**
   *
   * @type {string}
   * @memberof RawProfileResponse
   */
  avatarUrl: string | null;
  /**
   *
   * @type {string}
   * @memberof RawProfileResponse
   */
  location: string | null;
  /**
   *
   * @type {string}
   * @memberof RawProfileResponse
   */
  websiteUrl: string | null;
}

/**
 * Check if a given object implements the RawProfileResponse interface.
 */
export function instanceOfRawProfileResponse(value: object): value is RawProfileResponse {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('displayName' in value) || value['displayName'] === undefined) return false;
  if (!('username' in value) || value['username'] === undefined) return false;
  if (!('bio' in value) || value['bio'] === undefined) return false;
  if (!('avatarUrl' in value) || value['avatarUrl'] === undefined) return false;
  if (!('location' in value) || value['location'] === undefined) return false;
  if (!('websiteUrl' in value) || value['websiteUrl'] === undefined) return false;
  return true;
}

export function RawProfileResponseFromJSON(json: any): RawProfileResponse {
  return RawProfileResponseFromJSONTyped(json, false);
}

export function RawProfileResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RawProfileResponse {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    displayName: json['display_name'],
    username: json['username'],
    bio: json['bio'],
    avatarUrl: json['avatar_url'],
    location: json['location'],
    websiteUrl: json['website_url'],
  };
}

export function RawProfileResponseToJSON(json: any): RawProfileResponse {
  return RawProfileResponseToJSONTyped(json, false);
}

export function RawProfileResponseToJSONTyped(
  value?: RawProfileResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    display_name: value['displayName'],
    username: value['username'],
    bio: value['bio'],
    avatar_url: value['avatarUrl'],
    location: value['location'],
    website_url: value['websiteUrl'],
  };
}
