/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RegisterRequest
 */
export interface RegisterRequest {
  /**
   *
   * @type {string}
   * @memberof RegisterRequest
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof RegisterRequest
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof RegisterRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof RegisterRequest
   */
  username?: string;
  /**
   *
   * @type {any}
   * @memberof RegisterRequest
   */
  preferences?: any | null;
}

/**
 * Check if a given object implements the RegisterRequest interface.
 */
export function instanceOfRegisterRequest(value: object): value is RegisterRequest {
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('password' in value) || value['password'] === undefined) return false;
  return true;
}

export function RegisterRequestFromJSON(json: any): RegisterRequest {
  return RegisterRequestFromJSONTyped(json, false);
}

export function RegisterRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RegisterRequest {
  if (json == null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
    name: json['name'] == null ? undefined : json['name'],
    username: json['username'] == null ? undefined : json['username'],
    preferences: json['preferences'] == null ? undefined : json['preferences'],
  };
}

export function RegisterRequestToJSON(json: any): RegisterRequest {
  return RegisterRequestToJSONTyped(json, false);
}

export function RegisterRequestToJSONTyped(
  value?: RegisterRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value['email'],
    password: value['password'],
    name: value['name'],
    username: value['username'],
    preferences: value['preferences'],
  };
}
