/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SearchMarketplaceRequest
 */
export interface SearchMarketplaceRequest {
  /**
   *
   * @type {string}
   * @memberof SearchMarketplaceRequest
   */
  query: string;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof SearchMarketplaceRequest
   */
  filters?: { [key: string]: any };
  /**
   *
   * @type {number}
   * @memberof SearchMarketplaceRequest
   */
  limit?: number;
  /**
   *
   * @type {number}
   * @memberof SearchMarketplaceRequest
   */
  offset?: number;
}

/**
 * Check if a given object implements the SearchMarketplaceRequest interface.
 */
export function instanceOfSearchMarketplaceRequest(
  value: object
): value is SearchMarketplaceRequest {
  if (!('query' in value) || value['query'] === undefined) return false;
  return true;
}

export function SearchMarketplaceRequestFromJSON(json: any): SearchMarketplaceRequest {
  return SearchMarketplaceRequestFromJSONTyped(json, false);
}

export function SearchMarketplaceRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SearchMarketplaceRequest {
  if (json == null) {
    return json;
  }
  return {
    query: json['query'],
    filters: json['filters'] == null ? undefined : json['filters'],
    limit: json['limit'] == null ? undefined : json['limit'],
    offset: json['offset'] == null ? undefined : json['offset'],
  };
}

export function SearchMarketplaceRequestToJSON(json: any): SearchMarketplaceRequest {
  return SearchMarketplaceRequestToJSONTyped(json, false);
}

export function SearchMarketplaceRequestToJSONTyped(
  value?: SearchMarketplaceRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    query: value['query'],
    filters: value['filters'],
    limit: value['limit'],
    offset: value['offset'],
  };
}
