/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TeamMemberGroup } from './TeamMemberGroup';
import {
  TeamMemberGroupFromJSON,
  TeamMemberGroupFromJSONTyped,
  TeamMemberGroupToJSON,
  TeamMemberGroupToJSONTyped,
} from './TeamMemberGroup';

/**
 *
 * @export
 * @interface TeamMember
 */
export interface TeamMember {
  /**
   *
   * @type {string}
   * @memberof TeamMember
   */
  profileId: string;
  /**
   *
   * @type {string}
   * @memberof TeamMember
   */
  displayName: string | null;
  /**
   *
   * @type {string}
   * @memberof TeamMember
   */
  username: string | null;
  /**
   *
   * @type {string}
   * @memberof TeamMember
   */
  avatarUrl: string | null;
  /**
   *
   * @type {string}
   * @memberof TeamMember
   */
  role: string;
  /**
   *
   * @type {Date}
   * @memberof TeamMember
   */
  joinedAt: Date;
  /**
   *
   * @type {TeamMemberGroup}
   * @memberof TeamMember
   */
  group: TeamMemberGroup;
}

/**
 * Check if a given object implements the TeamMember interface.
 */
export function instanceOfTeamMember(value: object): value is TeamMember {
  if (!('profileId' in value) || value['profileId'] === undefined) return false;
  if (!('displayName' in value) || value['displayName'] === undefined) return false;
  if (!('username' in value) || value['username'] === undefined) return false;
  if (!('avatarUrl' in value) || value['avatarUrl'] === undefined) return false;
  if (!('role' in value) || value['role'] === undefined) return false;
  if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
  if (!('group' in value) || value['group'] === undefined) return false;
  return true;
}

export function TeamMemberFromJSON(json: any): TeamMember {
  return TeamMemberFromJSONTyped(json, false);
}

export function TeamMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamMember {
  if (json == null) {
    return json;
  }
  return {
    profileId: json['profileId'],
    displayName: json['displayName'],
    username: json['username'],
    avatarUrl: json['avatarUrl'],
    role: json['role'],
    joinedAt: new Date(json['joinedAt']),
    group: TeamMemberGroupFromJSON(json['group']),
  };
}

export function TeamMemberToJSON(json: any): TeamMember {
  return TeamMemberToJSONTyped(json, false);
}

export function TeamMemberToJSONTyped(
  value?: TeamMember | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    profileId: value['profileId'],
    displayName: value['displayName'],
    username: value['username'],
    avatarUrl: value['avatarUrl'],
    role: value['role'],
    joinedAt: value['joinedAt'].toISOString(),
    group: TeamMemberGroupToJSON(value['group']),
  };
}
