/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TeamMemberGroup
 */
export interface TeamMemberGroup {
  /**
   *
   * @type {string}
   * @memberof TeamMemberGroup
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof TeamMemberGroup
   */
  name: string;
}

/**
 * Check if a given object implements the TeamMemberGroup interface.
 */
export function instanceOfTeamMemberGroup(value: object): value is TeamMemberGroup {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function TeamMemberGroupFromJSON(json: any): TeamMemberGroup {
  return TeamMemberGroupFromJSONTyped(json, false);
}

export function TeamMemberGroupFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TeamMemberGroup {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
  };
}

export function TeamMemberGroupToJSON(json: any): TeamMemberGroup {
  return TeamMemberGroupToJSONTyped(json, false);
}

export function TeamMemberGroupToJSONTyped(
  value?: TeamMemberGroup | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
  };
}
