/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TokenRefreshResponse
 */
export interface TokenRefreshResponse {
  /**
   *
   * @type {string}
   * @memberof TokenRefreshResponse
   */
  accessToken: string;
  /**
   *
   * @type {string}
   * @memberof TokenRefreshResponse
   */
  refreshToken: string;
  /**
   *
   * @type {number}
   * @memberof TokenRefreshResponse
   */
  expiresIn: number;
}

/**
 * Check if a given object implements the TokenRefreshResponse interface.
 */
export function instanceOfTokenRefreshResponse(value: object): value is TokenRefreshResponse {
  if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
  if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
  if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
  return true;
}

export function TokenRefreshResponseFromJSON(json: any): TokenRefreshResponse {
  return TokenRefreshResponseFromJSONTyped(json, false);
}

export function TokenRefreshResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TokenRefreshResponse {
  if (json == null) {
    return json;
  }
  return {
    accessToken: json['access_token'],
    refreshToken: json['refresh_token'],
    expiresIn: json['expires_in'],
  };
}

export function TokenRefreshResponseToJSON(json: any): TokenRefreshResponse {
  return TokenRefreshResponseToJSONTyped(json, false);
}

export function TokenRefreshResponseToJSONTyped(
  value?: TokenRefreshResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    access_token: value['accessToken'],
    refresh_token: value['refreshToken'],
    expires_in: value['expiresIn'],
  };
}
