/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UninstallMarketplaceApp200Response
 */
export interface UninstallMarketplaceApp200Response {
  /**
   *
   * @type {boolean}
   * @memberof UninstallMarketplaceApp200Response
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UninstallMarketplaceApp200Response
   */
  success: boolean;
  /**
   *
   * @type {string}
   * @memberof UninstallMarketplaceApp200Response
   */
  message: string;
}

/**
 * Check if a given object implements the UninstallMarketplaceApp200Response interface.
 */
export function instanceOfUninstallMarketplaceApp200Response(
  value: object
): value is UninstallMarketplaceApp200Response {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function UninstallMarketplaceApp200ResponseFromJSON(
  json: any
): UninstallMarketplaceApp200Response {
  return UninstallMarketplaceApp200ResponseFromJSONTyped(json, false);
}

export function UninstallMarketplaceApp200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UninstallMarketplaceApp200Response {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    message: json['message'],
  };
}

export function UninstallMarketplaceApp200ResponseToJSON(
  json: any
): UninstallMarketplaceApp200Response {
  return UninstallMarketplaceApp200ResponseToJSONTyped(json, false);
}

export function UninstallMarketplaceApp200ResponseToJSONTyped(
  value?: UninstallMarketplaceApp200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    message: value['message'],
  };
}
