/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdatedProfileData
 */
export interface UpdatedProfileData {
  /**
   *
   * @type {string}
   * @memberof UpdatedProfileData
   */
  profileId: string;
  /**
   *
   * @type {string}
   * @memberof UpdatedProfileData
   */
  profileName: string;
  /**
   *
   * @type {boolean}
   * @memberof UpdatedProfileData
   */
  isActive: boolean;
  /**
   *
   * @type {string}
   * @memberof UpdatedProfileData
   */
  avatar: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdatedProfileData
   */
  bio: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdatedProfileData
   */
  location: string | null;
  /**
   *
   * @type {Date}
   * @memberof UpdatedProfileData
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the UpdatedProfileData interface.
 */
export function instanceOfUpdatedProfileData(value: object): value is UpdatedProfileData {
  if (!('profileId' in value) || value['profileId'] === undefined) return false;
  if (!('profileName' in value) || value['profileName'] === undefined) return false;
  if (!('isActive' in value) || value['isActive'] === undefined) return false;
  if (!('avatar' in value) || value['avatar'] === undefined) return false;
  if (!('bio' in value) || value['bio'] === undefined) return false;
  if (!('location' in value) || value['location'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  return true;
}

export function UpdatedProfileDataFromJSON(json: any): UpdatedProfileData {
  return UpdatedProfileDataFromJSONTyped(json, false);
}

export function UpdatedProfileDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdatedProfileData {
  if (json == null) {
    return json;
  }
  return {
    profileId: json['profileId'],
    profileName: json['profileName'],
    isActive: json['isActive'],
    avatar: json['avatar'],
    bio: json['bio'],
    location: json['location'],
    updatedAt: new Date(json['updatedAt']),
  };
}

export function UpdatedProfileDataToJSON(json: any): UpdatedProfileData {
  return UpdatedProfileDataToJSONTyped(json, false);
}

export function UpdatedProfileDataToJSONTyped(
  value?: UpdatedProfileData | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    profileId: value['profileId'],
    profileName: value['profileName'],
    isActive: value['isActive'],
    avatar: value['avatar'],
    bio: value['bio'],
    location: value['location'],
    updatedAt: value['updatedAt'].toISOString(),
  };
}
