/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdatedProfileData } from './UpdatedProfileData';
import {
  UpdatedProfileDataFromJSON,
  UpdatedProfileDataFromJSONTyped,
  UpdatedProfileDataToJSON,
  UpdatedProfileDataToJSONTyped,
} from './UpdatedProfileData';

/**
 *
 * @export
 * @interface UpdatedProfile
 */
export interface UpdatedProfile {
  /**
   *
   * @type {boolean}
   * @memberof UpdatedProfile
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UpdatedProfile
   */
  success: boolean;
  /**
   *
   * @type {UpdatedProfileData}
   * @memberof UpdatedProfile
   */
  data: UpdatedProfileData;
  /**
   *
   * @type {string}
   * @memberof UpdatedProfile
   */
  message?: string;
}

/**
 * Check if a given object implements the UpdatedProfile interface.
 */
export function instanceOfUpdatedProfile(value: object): value is UpdatedProfile {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function UpdatedProfileFromJSON(json: any): UpdatedProfile {
  return UpdatedProfileFromJSONTyped(json, false);
}

export function UpdatedProfileFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdatedProfile {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: UpdatedProfileDataFromJSON(json['data']),
    message: json['message'] == null ? undefined : json['message'],
  };
}

export function UpdatedProfileToJSON(json: any): UpdatedProfile {
  return UpdatedProfileToJSONTyped(json, false);
}

export function UpdatedProfileToJSONTyped(
  value?: UpdatedProfile | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: UpdatedProfileDataToJSON(value['data']),
    message: value['message'],
  };
}
