/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateProfileRequest
 */
export interface UpdateProfileRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateProfileRequest
   */
  profileName?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateProfileRequest
   */
  avatar?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateProfileRequest
   */
  bio?: string | null;
  /**
   *
   * @type {string}
   * @memberof UpdateProfileRequest
   */
  location?: string | null;
}

/**
 * Check if a given object implements the UpdateProfileRequest interface.
 */
export function instanceOfUpdateProfileRequest(value: object): value is UpdateProfileRequest {
  return true;
}

export function UpdateProfileRequestFromJSON(json: any): UpdateProfileRequest {
  return UpdateProfileRequestFromJSONTyped(json, false);
}

export function UpdateProfileRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateProfileRequest {
  if (json == null) {
    return json;
  }
  return {
    profileName: json['profileName'] == null ? undefined : json['profileName'],
    avatar: json['avatar'] == null ? undefined : json['avatar'],
    bio: json['bio'] == null ? undefined : json['bio'],
    location: json['location'] == null ? undefined : json['location'],
  };
}

export function UpdateProfileRequestToJSON(json: any): UpdateProfileRequest {
  return UpdateProfileRequestToJSONTyped(json, false);
}

export function UpdateProfileRequestToJSONTyped(
  value?: UpdateProfileRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    profileName: value['profileName'],
    avatar: value['avatar'],
    bio: value['bio'],
    location: value['location'],
  };
}
