/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateDeveloperAppRequest
 */
export interface UpdateDeveloperAppRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateDeveloperAppRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateDeveloperAppRequest
   */
  slug?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateDeveloperAppRequest
   */
  tagline?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateDeveloperAppRequest
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateDeveloperAppRequest
   */
  category?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateDeveloperAppRequest
   */
  iconUrl?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof UpdateDeveloperAppRequest
   */
  screenshots?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof UpdateDeveloperAppRequest
   */
  version?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateDeveloperAppRequest
   */
  pricingModel?: string;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof UpdateDeveloperAppRequest
   */
  pricingConfig?: { [key: string]: any };
  /**
   *
   * @type {Array<string>}
   * @memberof UpdateDeveloperAppRequest
   */
  supportedAudience?: Array<string>;
}

/**
 * Check if a given object implements the UpdateDeveloperAppRequest interface.
 */
export function instanceOfUpdateDeveloperAppRequest(
  value: object
): value is UpdateDeveloperAppRequest {
  return true;
}

export function UpdateDeveloperAppRequestFromJSON(json: any): UpdateDeveloperAppRequest {
  return UpdateDeveloperAppRequestFromJSONTyped(json, false);
}

export function UpdateDeveloperAppRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateDeveloperAppRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    slug: json['slug'] == null ? undefined : json['slug'],
    tagline: json['tagline'] == null ? undefined : json['tagline'],
    description: json['description'] == null ? undefined : json['description'],
    category: json['category'] == null ? undefined : json['category'],
    iconUrl: json['icon_url'] == null ? undefined : json['icon_url'],
    screenshots: json['screenshots'] == null ? undefined : json['screenshots'],
    version: json['version'] == null ? undefined : json['version'],
    pricingModel: json['pricing_model'] == null ? undefined : json['pricing_model'],
    pricingConfig: json['pricing_config'] == null ? undefined : json['pricing_config'],
    supportedAudience: json['supported_audience'] == null ? undefined : json['supported_audience'],
  };
}

export function UpdateDeveloperAppRequestToJSON(json: any): UpdateDeveloperAppRequest {
  return UpdateDeveloperAppRequestToJSONTyped(json, false);
}

export function UpdateDeveloperAppRequestToJSONTyped(
  value?: UpdateDeveloperAppRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    slug: value['slug'],
    tagline: value['tagline'],
    description: value['description'],
    category: value['category'],
    icon_url: value['iconUrl'],
    screenshots: value['screenshots'],
    version: value['version'],
    pricing_model: value['pricingModel'],
    pricing_config: value['pricingConfig'],
    supported_audience: value['supportedAudience'],
  };
}
