/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserMeDataApiKeyInfo } from './UserMeDataApiKeyInfo';
import {
  UserMeDataApiKeyInfoFromJSON,
  UserMeDataApiKeyInfoFromJSONTyped,
  UserMeDataApiKeyInfoToJSON,
  UserMeDataApiKeyInfoToJSONTyped,
} from './UserMeDataApiKeyInfo';

/**
 *
 * @export
 * @interface UserMeData
 */
export interface UserMeData {
  /**
   *
   * @type {string}
   * @memberof UserMeData
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof UserMeData
   */
  username: string | null;
  /**
   *
   * @type {string}
   * @memberof UserMeData
   */
  displayName: string;
  /**
   *
   * @type {string}
   * @memberof UserMeData
   */
  email: string | null;
  /**
   *
   * @type {string}
   * @memberof UserMeData
   */
  bio: string | null;
  /**
   *
   * @type {string}
   * @memberof UserMeData
   */
  location: string | null;
  /**
   *
   * @type {string}
   * @memberof UserMeData
   */
  website: string | null;
  /**
   *
   * @type {string}
   * @memberof UserMeData
   */
  avatar: string | null;
  /**
   *
   * @type {Date}
   * @memberof UserMeData
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof UserMeData
   */
  updatedAt: Date;
  /**
   *
   * @type {UserMeDataApiKeyInfo}
   * @memberof UserMeData
   */
  apiKeyInfo: UserMeDataApiKeyInfo;
}

/**
 * Check if a given object implements the UserMeData interface.
 */
export function instanceOfUserMeData(value: object): value is UserMeData {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('username' in value) || value['username'] === undefined) return false;
  if (!('displayName' in value) || value['displayName'] === undefined) return false;
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('bio' in value) || value['bio'] === undefined) return false;
  if (!('location' in value) || value['location'] === undefined) return false;
  if (!('website' in value) || value['website'] === undefined) return false;
  if (!('avatar' in value) || value['avatar'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  if (!('apiKeyInfo' in value) || value['apiKeyInfo'] === undefined) return false;
  return true;
}

export function UserMeDataFromJSON(json: any): UserMeData {
  return UserMeDataFromJSONTyped(json, false);
}

export function UserMeDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserMeData {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    username: json['username'],
    displayName: json['displayName'],
    email: json['email'],
    bio: json['bio'],
    location: json['location'],
    website: json['website'],
    avatar: json['avatar'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
    apiKeyInfo: UserMeDataApiKeyInfoFromJSON(json['apiKeyInfo']),
  };
}

export function UserMeDataToJSON(json: any): UserMeData {
  return UserMeDataToJSONTyped(json, false);
}

export function UserMeDataToJSONTyped(
  value?: UserMeData | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    username: value['username'],
    displayName: value['displayName'],
    email: value['email'],
    bio: value['bio'],
    location: value['location'],
    website: value['website'],
    avatar: value['avatar'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
    apiKeyInfo: UserMeDataApiKeyInfoToJSON(value['apiKeyInfo']),
  };
}
