/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserMeData } from './UserMeData';
import {
  UserMeDataFromJSON,
  UserMeDataFromJSONTyped,
  UserMeDataToJSON,
  UserMeDataToJSONTyped,
} from './UserMeData';

/**
 *
 * @export
 * @interface UserMe
 */
export interface UserMe {
  /**
   *
   * @type {boolean}
   * @memberof UserMe
   */
  ok: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UserMe
   */
  success: boolean;
  /**
   *
   * @type {UserMeData}
   * @memberof UserMe
   */
  data: UserMeData;
}

/**
 * Check if a given object implements the UserMe interface.
 */
export function instanceOfUserMe(value: object): value is UserMe {
  if (!('ok' in value) || value['ok'] === undefined) return false;
  if (!('success' in value) || value['success'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  return true;
}

export function UserMeFromJSON(json: any): UserMe {
  return UserMeFromJSONTyped(json, false);
}

export function UserMeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserMe {
  if (json == null) {
    return json;
  }
  return {
    ok: json['ok'],
    success: json['success'],
    data: UserMeDataFromJSON(json['data']),
  };
}

export function UserMeToJSON(json: any): UserMe {
  return UserMeToJSONTyped(json, false);
}

export function UserMeToJSONTyped(
  value?: UserMe | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    ok: value['ok'],
    success: value['success'],
    data: UserMeDataToJSON(value['data']),
  };
}
