/* tslint:disable */
/* eslint-disable */
/**
 * Oriva Platform API
 * Public API for 3rd party Oriva developers. Authenticate with your API key as a Bearer token.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserMeDataApiKeyInfo
 */
export interface UserMeDataApiKeyInfo {
  /**
   *
   * @type {string}
   * @memberof UserMeDataApiKeyInfo
   */
  keyId: string;
  /**
   *
   * @type {string}
   * @memberof UserMeDataApiKeyInfo
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof UserMeDataApiKeyInfo
   */
  userId: string;
  /**
   *
   * @type {Array<string>}
   * @memberof UserMeDataApiKeyInfo
   */
  permissions: Array<string>;
  /**
   *
   * @type {number}
   * @memberof UserMeDataApiKeyInfo
   */
  usageCount: number;
}

/**
 * Check if a given object implements the UserMeDataApiKeyInfo interface.
 */
export function instanceOfUserMeDataApiKeyInfo(value: object): value is UserMeDataApiKeyInfo {
  if (!('keyId' in value) || value['keyId'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('userId' in value) || value['userId'] === undefined) return false;
  if (!('permissions' in value) || value['permissions'] === undefined) return false;
  if (!('usageCount' in value) || value['usageCount'] === undefined) return false;
  return true;
}

export function UserMeDataApiKeyInfoFromJSON(json: any): UserMeDataApiKeyInfo {
  return UserMeDataApiKeyInfoFromJSONTyped(json, false);
}

export function UserMeDataApiKeyInfoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserMeDataApiKeyInfo {
  if (json == null) {
    return json;
  }
  return {
    keyId: json['keyId'],
    name: json['name'],
    userId: json['userId'],
    permissions: json['permissions'],
    usageCount: json['usageCount'],
  };
}

export function UserMeDataApiKeyInfoToJSON(json: any): UserMeDataApiKeyInfo {
  return UserMeDataApiKeyInfoToJSONTyped(json, false);
}

export function UserMeDataApiKeyInfoToJSONTyped(
  value?: UserMeDataApiKeyInfo | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    keyId: value['keyId'],
    name: value['name'],
    userId: value['userId'],
    permissions: value['permissions'],
    usageCount: value['usageCount'],
  };
}
